// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: dictator/speech/v1/alignment.proto

package dictatorspeechv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlignmentService_AlignTranscript_FullMethodName          = "/dictator.speech.v1.AlignmentService/AlignTranscript"
	AlignmentService_SubmitAlignTranscriptJob_FullMethodName = "/dictator.speech.v1.AlignmentService/SubmitAlignTranscriptJob"
	AlignmentService_GetAlignTranscriptJob_FullMethodName    = "/dictator.speech.v1.AlignmentService/GetAlignTranscriptJob"
)

// AlignmentServiceClient is the client API for AlignmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlignmentServiceClient interface {
	AlignTranscript(ctx context.Context, in *AlignTranscriptRequest, opts ...grpc.CallOption) (*AlignTranscriptResponse, error)
	SubmitAlignTranscriptJob(ctx context.Context, in *AlignTranscriptRequest, opts ...grpc.CallOption) (*SubmitAlignTranscriptJobResponse, error)
	GetAlignTranscriptJob(ctx context.Context, in *GetAlignTranscriptJobRequest, opts ...grpc.CallOption) (*GetAlignTranscriptJobResponse, error)
}

type alignmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlignmentServiceClient(cc grpc.ClientConnInterface) AlignmentServiceClient {
	return &alignmentServiceClient{cc}
}

func (c *alignmentServiceClient) AlignTranscript(ctx context.Context, in *AlignTranscriptRequest, opts ...grpc.CallOption) (*AlignTranscriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlignTranscriptResponse)
	err := c.cc.Invoke(ctx, AlignmentService_AlignTranscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alignmentServiceClient) SubmitAlignTranscriptJob(ctx context.Context, in *AlignTranscriptRequest, opts ...grpc.CallOption) (*SubmitAlignTranscriptJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAlignTranscriptJobResponse)
	err := c.cc.Invoke(ctx, AlignmentService_SubmitAlignTranscriptJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alignmentServiceClient) GetAlignTranscriptJob(ctx context.Context, in *GetAlignTranscriptJobRequest, opts ...grpc.CallOption) (*GetAlignTranscriptJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlignTranscriptJobResponse)
	err := c.cc.Invoke(ctx, AlignmentService_GetAlignTranscriptJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlignmentServiceServer is the server API for AlignmentService service.
// All implementations must embed UnimplementedAlignmentServiceServer
// for forward compatibility.
type AlignmentServiceServer interface {
	AlignTranscript(context.Context, *AlignTranscriptRequest) (*AlignTranscriptResponse, error)
	SubmitAlignTranscriptJob(context.Context, *AlignTranscriptRequest) (*SubmitAlignTranscriptJobResponse, error)
	GetAlignTranscriptJob(context.Context, *GetAlignTranscriptJobRequest) (*GetAlignTranscriptJobResponse, error)
	mustEmbedUnimplementedAlignmentServiceServer()
}

// UnimplementedAlignmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlignmentServiceServer struct{}

func (UnimplementedAlignmentServiceServer) AlignTranscript(context.Context, *AlignTranscriptRequest) (*AlignTranscriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlignTranscript not implemented")
}
func (UnimplementedAlignmentServiceServer) SubmitAlignTranscriptJob(context.Context, *AlignTranscriptRequest) (*SubmitAlignTranscriptJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAlignTranscriptJob not implemented")
}
func (UnimplementedAlignmentServiceServer) GetAlignTranscriptJob(context.Context, *GetAlignTranscriptJobRequest) (*GetAlignTranscriptJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlignTranscriptJob not implemented")
}
func (UnimplementedAlignmentServiceServer) mustEmbedUnimplementedAlignmentServiceServer() {}
func (UnimplementedAlignmentServiceServer) testEmbeddedByValue()                          {}

// UnsafeAlignmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlignmentServiceServer will
// result in compilation errors.
type UnsafeAlignmentServiceServer interface {
	mustEmbedUnimplementedAlignmentServiceServer()
}

func RegisterAlignmentServiceServer(s grpc.ServiceRegistrar, srv AlignmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAlignmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlignmentService_ServiceDesc, srv)
}

func _AlignmentService_AlignTranscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlignTranscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlignmentServiceServer).AlignTranscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlignmentService_AlignTranscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlignmentServiceServer).AlignTranscript(ctx, req.(*AlignTranscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlignmentService_SubmitAlignTranscriptJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlignTranscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlignmentServiceServer).SubmitAlignTranscriptJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlignmentService_SubmitAlignTranscriptJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlignmentServiceServer).SubmitAlignTranscriptJob(ctx, req.(*AlignTranscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlignmentService_GetAlignTranscriptJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlignTranscriptJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlignmentServiceServer).GetAlignTranscriptJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlignmentService_GetAlignTranscriptJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlignmentServiceServer).GetAlignTranscriptJob(ctx, req.(*GetAlignTranscriptJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlignmentService_ServiceDesc is the grpc.ServiceDesc for AlignmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlignmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dictator.speech.v1.AlignmentService",
	HandlerType: (*AlignmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AlignTranscript",
			Handler:    _AlignmentService_AlignTranscript_Handler,
		},
		{
			MethodName: "SubmitAlignTranscriptJob",
			Handler:    _AlignmentService_SubmitAlignTranscriptJob_Handler,
		},
		{
			MethodName: "GetAlignTranscriptJob",
			Handler:    _AlignmentService_GetAlignTranscriptJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dictator/speech/v1/alignment.proto",
}
