// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: dictator/speech/v1/alignment.proto

package dictatorspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlignmentJobState int32

const (
	AlignmentJobState_ALIGNMENT_JOB_STATE_UNSPECIFIED AlignmentJobState = 0
	AlignmentJobState_ALIGNMENT_JOB_STATE_QUEUED      AlignmentJobState = 1
	AlignmentJobState_ALIGNMENT_JOB_STATE_RUNNING     AlignmentJobState = 2
	AlignmentJobState_ALIGNMENT_JOB_STATE_SUCCEEDED   AlignmentJobState = 3
	AlignmentJobState_ALIGNMENT_JOB_STATE_FAILED      AlignmentJobState = 4
)

// Enum value maps for AlignmentJobState.
var (
	AlignmentJobState_name = map[int32]string{
		0: "ALIGNMENT_JOB_STATE_UNSPECIFIED",
		1: "ALIGNMENT_JOB_STATE_QUEUED",
		2: "ALIGNMENT_JOB_STATE_RUNNING",
		3: "ALIGNMENT_JOB_STATE_SUCCEEDED",
		4: "ALIGNMENT_JOB_STATE_FAILED",
	}
	AlignmentJobState_value = map[string]int32{
		"ALIGNMENT_JOB_STATE_UNSPECIFIED": 0,
		"ALIGNMENT_JOB_STATE_QUEUED":      1,
		"ALIGNMENT_JOB_STATE_RUNNING":     2,
		"ALIGNMENT_JOB_STATE_SUCCEEDED":   3,
		"ALIGNMENT_JOB_STATE_FAILED":      4,
	}
)

func (x AlignmentJobState) Enum() *AlignmentJobState {
	p := new(AlignmentJobState)
	*p = x
	return p
}

func (x AlignmentJobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlignmentJobState) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_alignment_proto_enumTypes[0].Descriptor()
}

func (AlignmentJobState) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_alignment_proto_enumTypes[0]
}

func (x AlignmentJobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlignmentJobState.Descriptor instead.
func (AlignmentJobState) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_alignment_proto_rawDescGZIP(), []int{0}
}

type AlignTranscriptRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AudioArtifactId string                 `protobuf:"bytes,1,opt,name=audio_artifact_id,json=audioArtifactId,proto3" json:"audio_artifact_id,omitempty"`
	// Types that are valid to be assigned to TranscriptSource:
	//
	//	*AlignTranscriptRequest_TranscriptText
	//	*AlignTranscriptRequest_TranscriptArtifactId
	TranscriptSource  isAlignTranscriptRequest_TranscriptSource `protobuf_oneof:"transcript_source"`
	LanguageCode      string                                    `protobuf:"bytes,4,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	RemovePunctuation bool                                      `protobuf:"varint,5,opt,name=remove_punctuation,json=removePunctuation,proto3" json:"remove_punctuation,omitempty"`
	IncludeSrtText    bool                                      `protobuf:"varint,6,opt,name=include_srt_text,json=includeSrtText,proto3" json:"include_srt_text,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AlignTranscriptRequest) Reset() {
	*x = AlignTranscriptRequest{}
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignTranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignTranscriptRequest) ProtoMessage() {}

func (x *AlignTranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignTranscriptRequest.ProtoReflect.Descriptor instead.
func (*AlignTranscriptRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_alignment_proto_rawDescGZIP(), []int{0}
}

func (x *AlignTranscriptRequest) GetAudioArtifactId() string {
	if x != nil {
		return x.AudioArtifactId
	}
	return ""
}

func (x *AlignTranscriptRequest) GetTranscriptSource() isAlignTranscriptRequest_TranscriptSource {
	if x != nil {
		return x.TranscriptSource
	}
	return nil
}

func (x *AlignTranscriptRequest) GetTranscriptText() string {
	if x != nil {
		if x, ok := x.TranscriptSource.(*AlignTranscriptRequest_TranscriptText); ok {
			return x.TranscriptText
		}
	}
	return ""
}

func (x *AlignTranscriptRequest) GetTranscriptArtifactId() string {
	if x != nil {
		if x, ok := x.TranscriptSource.(*AlignTranscriptRequest_TranscriptArtifactId); ok {
			return x.TranscriptArtifactId
		}
	}
	return ""
}

func (x *AlignTranscriptRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *AlignTranscriptRequest) GetRemovePunctuation() bool {
	if x != nil {
		return x.RemovePunctuation
	}
	return false
}

func (x *AlignTranscriptRequest) GetIncludeSrtText() bool {
	if x != nil {
		return x.IncludeSrtText
	}
	return false
}

type isAlignTranscriptRequest_TranscriptSource interface {
	isAlignTranscriptRequest_TranscriptSource()
}

type AlignTranscriptRequest_TranscriptText struct {
	TranscriptText string `protobuf:"bytes,2,opt,name=transcript_text,json=transcriptText,proto3,oneof"`
}

type AlignTranscriptRequest_TranscriptArtifactId struct {
	TranscriptArtifactId string `protobuf:"bytes,3,opt,name=transcript_artifact_id,json=transcriptArtifactId,proto3,oneof"`
}

func (*AlignTranscriptRequest_TranscriptText) isAlignTranscriptRequest_TranscriptSource() {}

func (*AlignTranscriptRequest_TranscriptArtifactId) isAlignTranscriptRequest_TranscriptSource() {}

type AlignTranscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LanguageCode  string                 `protobuf:"bytes,1,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	Words         []*WordSegment         `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	SrtText       string                 `protobuf:"bytes,3,opt,name=srt_text,json=srtText,proto3" json:"srt_text,omitempty"`
	SrtArtifactId string                 `protobuf:"bytes,4,opt,name=srt_artifact_id,json=srtArtifactId,proto3" json:"srt_artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlignTranscriptResponse) Reset() {
	*x = AlignTranscriptResponse{}
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignTranscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignTranscriptResponse) ProtoMessage() {}

func (x *AlignTranscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignTranscriptResponse.ProtoReflect.Descriptor instead.
func (*AlignTranscriptResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_alignment_proto_rawDescGZIP(), []int{1}
}

func (x *AlignTranscriptResponse) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *AlignTranscriptResponse) GetWords() []*WordSegment {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *AlignTranscriptResponse) GetSrtText() string {
	if x != nil {
		return x.SrtText
	}
	return ""
}

func (x *AlignTranscriptResponse) GetSrtArtifactId() string {
	if x != nil {
		return x.SrtArtifactId
	}
	return ""
}

type SubmitAlignTranscriptJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         AlignmentJobState      `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.AlignmentJobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAlignTranscriptJobResponse) Reset() {
	*x = SubmitAlignTranscriptJobResponse{}
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAlignTranscriptJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAlignTranscriptJobResponse) ProtoMessage() {}

func (x *SubmitAlignTranscriptJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAlignTranscriptJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitAlignTranscriptJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_alignment_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitAlignTranscriptJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitAlignTranscriptJobResponse) GetState() AlignmentJobState {
	if x != nil {
		return x.State
	}
	return AlignmentJobState_ALIGNMENT_JOB_STATE_UNSPECIFIED
}

type GetAlignTranscriptJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlignTranscriptJobRequest) Reset() {
	*x = GetAlignTranscriptJobRequest{}
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlignTranscriptJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlignTranscriptJobRequest) ProtoMessage() {}

func (x *GetAlignTranscriptJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlignTranscriptJobRequest.ProtoReflect.Descriptor instead.
func (*GetAlignTranscriptJobRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_alignment_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlignTranscriptJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetAlignTranscriptJobResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	JobId                 string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State                 AlignmentJobState      `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.AlignmentJobState" json:"state,omitempty"`
	ErrorCode             string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LanguageCode          string                 `protobuf:"bytes,5,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	Words                 []*WordSegment         `protobuf:"bytes,6,rep,name=words,proto3" json:"words,omitempty"`
	SrtText               string                 `protobuf:"bytes,7,opt,name=srt_text,json=srtText,proto3" json:"srt_text,omitempty"`
	SrtArtifactId         string                 `protobuf:"bytes,8,opt,name=srt_artifact_id,json=srtArtifactId,proto3" json:"srt_artifact_id,omitempty"`
	CreatedAtUnixSeconds  float64                `protobuf:"fixed64,9,opt,name=created_at_unix_seconds,json=createdAtUnixSeconds,proto3" json:"created_at_unix_seconds,omitempty"`
	StartedAtUnixSeconds  float64                `protobuf:"fixed64,10,opt,name=started_at_unix_seconds,json=startedAtUnixSeconds,proto3" json:"started_at_unix_seconds,omitempty"`
	FinishedAtUnixSeconds float64                `protobuf:"fixed64,11,opt,name=finished_at_unix_seconds,json=finishedAtUnixSeconds,proto3" json:"finished_at_unix_seconds,omitempty"`
	SourceArtifactId      string                 `protobuf:"bytes,12,opt,name=source_artifact_id,json=sourceArtifactId,proto3" json:"source_artifact_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetAlignTranscriptJobResponse) Reset() {
	*x = GetAlignTranscriptJobResponse{}
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlignTranscriptJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlignTranscriptJobResponse) ProtoMessage() {}

func (x *GetAlignTranscriptJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_alignment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlignTranscriptJobResponse.ProtoReflect.Descriptor instead.
func (*GetAlignTranscriptJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_alignment_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlignTranscriptJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetAlignTranscriptJobResponse) GetState() AlignmentJobState {
	if x != nil {
		return x.State
	}
	return AlignmentJobState_ALIGNMENT_JOB_STATE_UNSPECIFIED
}

func (x *GetAlignTranscriptJobResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetAlignTranscriptJobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetAlignTranscriptJobResponse) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *GetAlignTranscriptJobResponse) GetWords() []*WordSegment {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *GetAlignTranscriptJobResponse) GetSrtText() string {
	if x != nil {
		return x.SrtText
	}
	return ""
}

func (x *GetAlignTranscriptJobResponse) GetSrtArtifactId() string {
	if x != nil {
		return x.SrtArtifactId
	}
	return ""
}

func (x *GetAlignTranscriptJobResponse) GetCreatedAtUnixSeconds() float64 {
	if x != nil {
		return x.CreatedAtUnixSeconds
	}
	return 0
}

func (x *GetAlignTranscriptJobResponse) GetStartedAtUnixSeconds() float64 {
	if x != nil {
		return x.StartedAtUnixSeconds
	}
	return 0
}

func (x *GetAlignTranscriptJobResponse) GetFinishedAtUnixSeconds() float64 {
	if x != nil {
		return x.FinishedAtUnixSeconds
	}
	return 0
}

func (x *GetAlignTranscriptJobResponse) GetSourceArtifactId() string {
	if x != nil {
		return x.SourceArtifactId
	}
	return ""
}

var File_dictator_speech_v1_alignment_proto protoreflect.FileDescriptor

const file_dictator_speech_v1_alignment_proto_rawDesc = "" +
	"\n" +
	"\"dictator/speech/v1/alignment.proto\x12\x12dictator.speech.v1\x1a\x1fdictator/speech/v1/common.proto\"\xba\x02\n" +
	"\x16AlignTranscriptRequest\x12*\n" +
	"\x11audio_artifact_id\x18\x01 \x01(\tR\x0faudioArtifactId\x12)\n" +
	"\x0ftranscript_text\x18\x02 \x01(\tH\x00R\x0etranscriptText\x126\n" +
	"\x16transcript_artifact_id\x18\x03 \x01(\tH\x00R\x14transcriptArtifactId\x12#\n" +
	"\rlanguage_code\x18\x04 \x01(\tR\flanguageCode\x12-\n" +
	"\x12remove_punctuation\x18\x05 \x01(\bR\x11removePunctuation\x12(\n" +
	"\x10include_srt_text\x18\x06 \x01(\bR\x0eincludeSrtTextB\x13\n" +
	"\x11transcript_source\"\xb8\x01\n" +
	"\x17AlignTranscriptResponse\x12#\n" +
	"\rlanguage_code\x18\x01 \x01(\tR\flanguageCode\x125\n" +
	"\x05words\x18\x02 \x03(\v2\x1f.dictator.speech.v1.WordSegmentR\x05words\x12\x19\n" +
	"\bsrt_text\x18\x03 \x01(\tR\asrtText\x12&\n" +
	"\x0fsrt_artifact_id\x18\x04 \x01(\tR\rsrtArtifactId\"v\n" +
	" SubmitAlignTranscriptJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12;\n" +
	"\x05state\x18\x02 \x01(\x0e2%.dictator.speech.v1.AlignmentJobStateR\x05state\"5\n" +
	"\x1cGetAlignTranscriptJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xab\x04\n" +
	"\x1dGetAlignTranscriptJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12;\n" +
	"\x05state\x18\x02 \x01(\x0e2%.dictator.speech.v1.AlignmentJobStateR\x05state\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12#\n" +
	"\rlanguage_code\x18\x05 \x01(\tR\flanguageCode\x125\n" +
	"\x05words\x18\x06 \x03(\v2\x1f.dictator.speech.v1.WordSegmentR\x05words\x12\x19\n" +
	"\bsrt_text\x18\a \x01(\tR\asrtText\x12&\n" +
	"\x0fsrt_artifact_id\x18\b \x01(\tR\rsrtArtifactId\x125\n" +
	"\x17created_at_unix_seconds\x18\t \x01(\x01R\x14createdAtUnixSeconds\x125\n" +
	"\x17started_at_unix_seconds\x18\n" +
	" \x01(\x01R\x14startedAtUnixSeconds\x127\n" +
	"\x18finished_at_unix_seconds\x18\v \x01(\x01R\x15finishedAtUnixSeconds\x12,\n" +
	"\x12source_artifact_id\x18\f \x01(\tR\x10sourceArtifactId*\xbc\x01\n" +
	"\x11AlignmentJobState\x12#\n" +
	"\x1fALIGNMENT_JOB_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aALIGNMENT_JOB_STATE_QUEUED\x10\x01\x12\x1f\n" +
	"\x1bALIGNMENT_JOB_STATE_RUNNING\x10\x02\x12!\n" +
	"\x1dALIGNMENT_JOB_STATE_SUCCEEDED\x10\x03\x12\x1e\n" +
	"\x1aALIGNMENT_JOB_STATE_FAILED\x10\x042\xfa\x02\n" +
	"\x10AlignmentService\x12j\n" +
	"\x0fAlignTranscript\x12*.dictator.speech.v1.AlignTranscriptRequest\x1a+.dictator.speech.v1.AlignTranscriptResponse\x12|\n" +
	"\x18SubmitAlignTranscriptJob\x12*.dictator.speech.v1.AlignTranscriptRequest\x1a4.dictator.speech.v1.SubmitAlignTranscriptJobResponse\x12|\n" +
	"\x15GetAlignTranscriptJob\x120.dictator.speech.v1.GetAlignTranscriptJobRequest\x1a1.dictator.speech.v1.GetAlignTranscriptJobResponseBGZEgithub.com/tyemirov/dictator/sdk/go/dictatorspeechv1;dictatorspeechv1b\x06proto3"

var (
	file_dictator_speech_v1_alignment_proto_rawDescOnce sync.Once
	file_dictator_speech_v1_alignment_proto_rawDescData []byte
)

func file_dictator_speech_v1_alignment_proto_rawDescGZIP() []byte {
	file_dictator_speech_v1_alignment_proto_rawDescOnce.Do(func() {
		file_dictator_speech_v1_alignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_alignment_proto_rawDesc), len(file_dictator_speech_v1_alignment_proto_rawDesc)))
	})
	return file_dictator_speech_v1_alignment_proto_rawDescData
}

var file_dictator_speech_v1_alignment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dictator_speech_v1_alignment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dictator_speech_v1_alignment_proto_goTypes = []any{
	(AlignmentJobState)(0),                   // 0: dictator.speech.v1.AlignmentJobState
	(*AlignTranscriptRequest)(nil),           // 1: dictator.speech.v1.AlignTranscriptRequest
	(*AlignTranscriptResponse)(nil),          // 2: dictator.speech.v1.AlignTranscriptResponse
	(*SubmitAlignTranscriptJobResponse)(nil), // 3: dictator.speech.v1.SubmitAlignTranscriptJobResponse
	(*GetAlignTranscriptJobRequest)(nil),     // 4: dictator.speech.v1.GetAlignTranscriptJobRequest
	(*GetAlignTranscriptJobResponse)(nil),    // 5: dictator.speech.v1.GetAlignTranscriptJobResponse
	(*WordSegment)(nil),                      // 6: dictator.speech.v1.WordSegment
}
var file_dictator_speech_v1_alignment_proto_depIdxs = []int32{
	6, // 0: dictator.speech.v1.AlignTranscriptResponse.words:type_name -> dictator.speech.v1.WordSegment
	0, // 1: dictator.speech.v1.SubmitAlignTranscriptJobResponse.state:type_name -> dictator.speech.v1.AlignmentJobState
	0, // 2: dictator.speech.v1.GetAlignTranscriptJobResponse.state:type_name -> dictator.speech.v1.AlignmentJobState
	6, // 3: dictator.speech.v1.GetAlignTranscriptJobResponse.words:type_name -> dictator.speech.v1.WordSegment
	1, // 4: dictator.speech.v1.AlignmentService.AlignTranscript:input_type -> dictator.speech.v1.AlignTranscriptRequest
	1, // 5: dictator.speech.v1.AlignmentService.SubmitAlignTranscriptJob:input_type -> dictator.speech.v1.AlignTranscriptRequest
	4, // 6: dictator.speech.v1.AlignmentService.GetAlignTranscriptJob:input_type -> dictator.speech.v1.GetAlignTranscriptJobRequest
	2, // 7: dictator.speech.v1.AlignmentService.AlignTranscript:output_type -> dictator.speech.v1.AlignTranscriptResponse
	3, // 8: dictator.speech.v1.AlignmentService.SubmitAlignTranscriptJob:output_type -> dictator.speech.v1.SubmitAlignTranscriptJobResponse
	5, // 9: dictator.speech.v1.AlignmentService.GetAlignTranscriptJob:output_type -> dictator.speech.v1.GetAlignTranscriptJobResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dictator_speech_v1_alignment_proto_init() }
func file_dictator_speech_v1_alignment_proto_init() {
	if File_dictator_speech_v1_alignment_proto != nil {
		return
	}
	file_dictator_speech_v1_common_proto_init()
	file_dictator_speech_v1_alignment_proto_msgTypes[0].OneofWrappers = []any{
		(*AlignTranscriptRequest_TranscriptText)(nil),
		(*AlignTranscriptRequest_TranscriptArtifactId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_alignment_proto_rawDesc), len(file_dictator_speech_v1_alignment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dictator_speech_v1_alignment_proto_goTypes,
		DependencyIndexes: file_dictator_speech_v1_alignment_proto_depIdxs,
		EnumInfos:         file_dictator_speech_v1_alignment_proto_enumTypes,
		MessageInfos:      file_dictator_speech_v1_alignment_proto_msgTypes,
	}.Build()
	File_dictator_speech_v1_alignment_proto = out.File
	file_dictator_speech_v1_alignment_proto_goTypes = nil
	file_dictator_speech_v1_alignment_proto_depIdxs = nil
}
