// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: dictator/speech/v1/artifacts.proto

package dictatorspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadArtifactMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArtifactMetadata) Reset() {
	*x = UploadArtifactMetadata{}
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArtifactMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArtifactMetadata) ProtoMessage() {}

func (x *UploadArtifactMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArtifactMetadata.ProtoReflect.Descriptor instead.
func (*UploadArtifactMetadata) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_artifacts_proto_rawDescGZIP(), []int{0}
}

func (x *UploadArtifactMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadArtifactMetadata) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type UploadArtifactChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadArtifactChunk_Metadata
	//	*UploadArtifactChunk_Content
	Payload       isUploadArtifactChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArtifactChunk) Reset() {
	*x = UploadArtifactChunk{}
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArtifactChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArtifactChunk) ProtoMessage() {}

func (x *UploadArtifactChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArtifactChunk.ProtoReflect.Descriptor instead.
func (*UploadArtifactChunk) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_artifacts_proto_rawDescGZIP(), []int{1}
}

func (x *UploadArtifactChunk) GetPayload() isUploadArtifactChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadArtifactChunk) GetMetadata() *UploadArtifactMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadArtifactChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadArtifactChunk) GetContent() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadArtifactChunk_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isUploadArtifactChunk_Payload interface {
	isUploadArtifactChunk_Payload()
}

type UploadArtifactChunk_Metadata struct {
	Metadata *UploadArtifactMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadArtifactChunk_Content struct {
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*UploadArtifactChunk_Metadata) isUploadArtifactChunk_Payload() {}

func (*UploadArtifactChunk_Content) isUploadArtifactChunk_Payload() {}

type UploadArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *ArtifactRef           `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArtifactResponse) Reset() {
	*x = UploadArtifactResponse{}
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArtifactResponse) ProtoMessage() {}

func (x *UploadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArtifactResponse.ProtoReflect.Descriptor instead.
func (*UploadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_artifacts_proto_rawDescGZIP(), []int{2}
}

func (x *UploadArtifactResponse) GetArtifact() *ArtifactRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type DownloadArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactRequest) Reset() {
	*x = DownloadArtifactRequest{}
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactRequest) ProtoMessage() {}

func (x *DownloadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactRequest.ProtoReflect.Descriptor instead.
func (*DownloadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_artifacts_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *DownloadArtifactRequest) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type DownloadArtifactChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *ArtifactRef           `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactChunk) Reset() {
	*x = DownloadArtifactChunk{}
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactChunk) ProtoMessage() {}

func (x *DownloadArtifactChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_artifacts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactChunk.ProtoReflect.Descriptor instead.
func (*DownloadArtifactChunk) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_artifacts_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadArtifactChunk) GetArtifact() *ArtifactRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *DownloadArtifactChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DownloadArtifactChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadArtifactChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_dictator_speech_v1_artifacts_proto protoreflect.FileDescriptor

const file_dictator_speech_v1_artifacts_proto_rawDesc = "" +
	"\n" +
	"\"dictator/speech/v1/artifacts.proto\x12\x12dictator.speech.v1\x1a\x1fdictator/speech/v1/common.proto\"S\n" +
	"\x16UploadArtifactMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\"\x86\x01\n" +
	"\x13UploadArtifactChunk\x12H\n" +
	"\bmetadata\x18\x01 \x01(\v2*.dictator.speech.v1.UploadArtifactMetadataH\x00R\bmetadata\x12\x1a\n" +
	"\acontent\x18\x02 \x01(\fH\x00R\acontentB\t\n" +
	"\apayload\"U\n" +
	"\x16UploadArtifactResponse\x12;\n" +
	"\bartifact\x18\x01 \x01(\v2\x1f.dictator.speech.v1.ArtifactRefR\bartifact\"Y\n" +
	"\x17DownloadArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\x03R\tchunkSize\"\x98\x01\n" +
	"\x15DownloadArtifactChunk\x12;\n" +
	"\bartifact\x18\x01 \x01(\v2\x1f.dictator.speech.v1.ArtifactRefR\bartifact\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof2\xe8\x01\n" +
	"\x0fArtifactService\x12g\n" +
	"\x0eUploadArtifact\x12'.dictator.speech.v1.UploadArtifactChunk\x1a*.dictator.speech.v1.UploadArtifactResponse(\x01\x12l\n" +
	"\x10DownloadArtifact\x12+.dictator.speech.v1.DownloadArtifactRequest\x1a).dictator.speech.v1.DownloadArtifactChunk0\x01BGZEgithub.com/tyemirov/dictator/sdk/go/dictatorspeechv1;dictatorspeechv1b\x06proto3"

var (
	file_dictator_speech_v1_artifacts_proto_rawDescOnce sync.Once
	file_dictator_speech_v1_artifacts_proto_rawDescData []byte
)

func file_dictator_speech_v1_artifacts_proto_rawDescGZIP() []byte {
	file_dictator_speech_v1_artifacts_proto_rawDescOnce.Do(func() {
		file_dictator_speech_v1_artifacts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_artifacts_proto_rawDesc), len(file_dictator_speech_v1_artifacts_proto_rawDesc)))
	})
	return file_dictator_speech_v1_artifacts_proto_rawDescData
}

var file_dictator_speech_v1_artifacts_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dictator_speech_v1_artifacts_proto_goTypes = []any{
	(*UploadArtifactMetadata)(nil),  // 0: dictator.speech.v1.UploadArtifactMetadata
	(*UploadArtifactChunk)(nil),     // 1: dictator.speech.v1.UploadArtifactChunk
	(*UploadArtifactResponse)(nil),  // 2: dictator.speech.v1.UploadArtifactResponse
	(*DownloadArtifactRequest)(nil), // 3: dictator.speech.v1.DownloadArtifactRequest
	(*DownloadArtifactChunk)(nil),   // 4: dictator.speech.v1.DownloadArtifactChunk
	(*ArtifactRef)(nil),             // 5: dictator.speech.v1.ArtifactRef
}
var file_dictator_speech_v1_artifacts_proto_depIdxs = []int32{
	0, // 0: dictator.speech.v1.UploadArtifactChunk.metadata:type_name -> dictator.speech.v1.UploadArtifactMetadata
	5, // 1: dictator.speech.v1.UploadArtifactResponse.artifact:type_name -> dictator.speech.v1.ArtifactRef
	5, // 2: dictator.speech.v1.DownloadArtifactChunk.artifact:type_name -> dictator.speech.v1.ArtifactRef
	1, // 3: dictator.speech.v1.ArtifactService.UploadArtifact:input_type -> dictator.speech.v1.UploadArtifactChunk
	3, // 4: dictator.speech.v1.ArtifactService.DownloadArtifact:input_type -> dictator.speech.v1.DownloadArtifactRequest
	2, // 5: dictator.speech.v1.ArtifactService.UploadArtifact:output_type -> dictator.speech.v1.UploadArtifactResponse
	4, // 6: dictator.speech.v1.ArtifactService.DownloadArtifact:output_type -> dictator.speech.v1.DownloadArtifactChunk
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dictator_speech_v1_artifacts_proto_init() }
func file_dictator_speech_v1_artifacts_proto_init() {
	if File_dictator_speech_v1_artifacts_proto != nil {
		return
	}
	file_dictator_speech_v1_common_proto_init()
	file_dictator_speech_v1_artifacts_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadArtifactChunk_Metadata)(nil),
		(*UploadArtifactChunk_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_artifacts_proto_rawDesc), len(file_dictator_speech_v1_artifacts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dictator_speech_v1_artifacts_proto_goTypes,
		DependencyIndexes: file_dictator_speech_v1_artifacts_proto_depIdxs,
		MessageInfos:      file_dictator_speech_v1_artifacts_proto_msgTypes,
	}.Build()
	File_dictator_speech_v1_artifacts_proto = out.File
	file_dictator_speech_v1_artifacts_proto_goTypes = nil
	file_dictator_speech_v1_artifacts_proto_depIdxs = nil
}
