// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: dictator/speech/v1/common.proto

package dictatorspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioContainer int32

const (
	AudioContainer_AUDIO_CONTAINER_UNSPECIFIED AudioContainer = 0
	AudioContainer_AUDIO_CONTAINER_WAV         AudioContainer = 1
)

// Enum value maps for AudioContainer.
var (
	AudioContainer_name = map[int32]string{
		0: "AUDIO_CONTAINER_UNSPECIFIED",
		1: "AUDIO_CONTAINER_WAV",
	}
	AudioContainer_value = map[string]int32{
		"AUDIO_CONTAINER_UNSPECIFIED": 0,
		"AUDIO_CONTAINER_WAV":         1,
	}
)

func (x AudioContainer) Enum() *AudioContainer {
	p := new(AudioContainer)
	*p = x
	return p
}

func (x AudioContainer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioContainer) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_common_proto_enumTypes[0].Descriptor()
}

func (AudioContainer) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_common_proto_enumTypes[0]
}

func (x AudioContainer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioContainer.Descriptor instead.
func (AudioContainer) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{0}
}

type AudioCodec int32

const (
	AudioCodec_AUDIO_CODEC_UNSPECIFIED AudioCodec = 0
	AudioCodec_AUDIO_CODEC_PCM_S16LE   AudioCodec = 1
)

// Enum value maps for AudioCodec.
var (
	AudioCodec_name = map[int32]string{
		0: "AUDIO_CODEC_UNSPECIFIED",
		1: "AUDIO_CODEC_PCM_S16LE",
	}
	AudioCodec_value = map[string]int32{
		"AUDIO_CODEC_UNSPECIFIED": 0,
		"AUDIO_CODEC_PCM_S16LE":   1,
	}
)

func (x AudioCodec) Enum() *AudioCodec {
	p := new(AudioCodec)
	*p = x
	return p
}

func (x AudioCodec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioCodec) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_common_proto_enumTypes[1].Descriptor()
}

func (AudioCodec) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_common_proto_enumTypes[1]
}

func (x AudioCodec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioCodec.Descriptor instead.
func (AudioCodec) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{1}
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	AudioMetadata *AudioMetadata         `protobuf:"bytes,6,opt,name=audio_metadata,json=audioMetadata,proto3" json:"audio_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_dictator_speech_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRef) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactRef) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ArtifactRef) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ArtifactRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactRef) GetAudioMetadata() *AudioMetadata {
	if x != nil {
		return x.AudioMetadata
	}
	return nil
}

type AudioFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     AudioContainer         `protobuf:"varint,1,opt,name=container,proto3,enum=dictator.speech.v1.AudioContainer" json:"container,omitempty"`
	Codec         AudioCodec             `protobuf:"varint,2,opt,name=codec,proto3,enum=dictator.speech.v1.AudioCodec" json:"codec,omitempty"`
	SampleRateHz  int32                  `protobuf:"varint,3,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	ChannelCount  int32                  `protobuf:"varint,4,opt,name=channel_count,json=channelCount,proto3" json:"channel_count,omitempty"`
	BitDepth      int32                  `protobuf:"varint,5,opt,name=bit_depth,json=bitDepth,proto3" json:"bit_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFormat) Reset() {
	*x = AudioFormat{}
	mi := &file_dictator_speech_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFormat) ProtoMessage() {}

func (x *AudioFormat) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFormat.ProtoReflect.Descriptor instead.
func (*AudioFormat) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *AudioFormat) GetContainer() AudioContainer {
	if x != nil {
		return x.Container
	}
	return AudioContainer_AUDIO_CONTAINER_UNSPECIFIED
}

func (x *AudioFormat) GetCodec() AudioCodec {
	if x != nil {
		return x.Codec
	}
	return AudioCodec_AUDIO_CODEC_UNSPECIFIED
}

func (x *AudioFormat) GetSampleRateHz() int32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *AudioFormat) GetChannelCount() int32 {
	if x != nil {
		return x.ChannelCount
	}
	return 0
}

func (x *AudioFormat) GetBitDepth() int32 {
	if x != nil {
		return x.BitDepth
	}
	return 0
}

type AudioMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Container       string                 `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Codec           string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	SampleRateHz    int32                  `protobuf:"varint,3,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	ChannelCount    int32                  `protobuf:"varint,4,opt,name=channel_count,json=channelCount,proto3" json:"channel_count,omitempty"`
	BitDepth        int32                  `protobuf:"varint,5,opt,name=bit_depth,json=bitDepth,proto3" json:"bit_depth,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AudioMetadata) Reset() {
	*x = AudioMetadata{}
	mi := &file_dictator_speech_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioMetadata) ProtoMessage() {}

func (x *AudioMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioMetadata.ProtoReflect.Descriptor instead.
func (*AudioMetadata) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *AudioMetadata) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *AudioMetadata) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *AudioMetadata) GetSampleRateHz() int32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *AudioMetadata) GetChannelCount() int32 {
	if x != nil {
		return x.ChannelCount
	}
	return 0
}

func (x *AudioMetadata) GetBitDepth() int32 {
	if x != nil {
		return x.BitDepth
	}
	return 0
}

func (x *AudioMetadata) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type WordSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	StartSeconds  float64                `protobuf:"fixed64,2,opt,name=start_seconds,json=startSeconds,proto3" json:"start_seconds,omitempty"`
	EndSeconds    float64                `protobuf:"fixed64,3,opt,name=end_seconds,json=endSeconds,proto3" json:"end_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordSegment) Reset() {
	*x = WordSegment{}
	mi := &file_dictator_speech_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordSegment) ProtoMessage() {}

func (x *WordSegment) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordSegment.ProtoReflect.Descriptor instead.
func (*WordSegment) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *WordSegment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WordSegment) GetStartSeconds() float64 {
	if x != nil {
		return x.StartSeconds
	}
	return 0
}

func (x *WordSegment) GetEndSeconds() float64 {
	if x != nil {
		return x.EndSeconds
	}
	return 0
}

type TimelineSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	StartSeconds  float64                `protobuf:"fixed64,2,opt,name=start_seconds,json=startSeconds,proto3" json:"start_seconds,omitempty"`
	EndSeconds    float64                `protobuf:"fixed64,3,opt,name=end_seconds,json=endSeconds,proto3" json:"end_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineSegment) Reset() {
	*x = TimelineSegment{}
	mi := &file_dictator_speech_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineSegment) ProtoMessage() {}

func (x *TimelineSegment) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineSegment.ProtoReflect.Descriptor instead.
func (*TimelineSegment) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *TimelineSegment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TimelineSegment) GetStartSeconds() float64 {
	if x != nil {
		return x.StartSeconds
	}
	return 0
}

func (x *TimelineSegment) GetEndSeconds() float64 {
	if x != nil {
		return x.EndSeconds
	}
	return 0
}

var File_dictator_speech_v1_common_proto protoreflect.FileDescriptor

const file_dictator_speech_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1fdictator/speech/v1/common.proto\x12\x12dictator.speech.v1\"\xea\x01\n" +
	"\vArtifactRef\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12H\n" +
	"\x0eaudio_metadata\x18\x06 \x01(\v2!.dictator.speech.v1.AudioMetadataR\raudioMetadata\"\xed\x01\n" +
	"\vAudioFormat\x12@\n" +
	"\tcontainer\x18\x01 \x01(\x0e2\".dictator.speech.v1.AudioContainerR\tcontainer\x124\n" +
	"\x05codec\x18\x02 \x01(\x0e2\x1e.dictator.speech.v1.AudioCodecR\x05codec\x12$\n" +
	"\x0esample_rate_hz\x18\x03 \x01(\x05R\fsampleRateHz\x12#\n" +
	"\rchannel_count\x18\x04 \x01(\x05R\fchannelCount\x12\x1b\n" +
	"\tbit_depth\x18\x05 \x01(\x05R\bbitDepth\"\xd6\x01\n" +
	"\rAudioMetadata\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x12$\n" +
	"\x0esample_rate_hz\x18\x03 \x01(\x05R\fsampleRateHz\x12#\n" +
	"\rchannel_count\x18\x04 \x01(\x05R\fchannelCount\x12\x1b\n" +
	"\tbit_depth\x18\x05 \x01(\x05R\bbitDepth\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\x01R\x0fdurationSeconds\"m\n" +
	"\vWordSegment\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\rstart_seconds\x18\x02 \x01(\x01R\fstartSeconds\x12\x1f\n" +
	"\vend_seconds\x18\x03 \x01(\x01R\n" +
	"endSeconds\"q\n" +
	"\x0fTimelineSegment\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\rstart_seconds\x18\x02 \x01(\x01R\fstartSeconds\x12\x1f\n" +
	"\vend_seconds\x18\x03 \x01(\x01R\n" +
	"endSeconds*J\n" +
	"\x0eAudioContainer\x12\x1f\n" +
	"\x1bAUDIO_CONTAINER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AUDIO_CONTAINER_WAV\x10\x01*D\n" +
	"\n" +
	"AudioCodec\x12\x1b\n" +
	"\x17AUDIO_CODEC_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15AUDIO_CODEC_PCM_S16LE\x10\x01BGZEgithub.com/tyemirov/dictator/sdk/go/dictatorspeechv1;dictatorspeechv1b\x06proto3"

var (
	file_dictator_speech_v1_common_proto_rawDescOnce sync.Once
	file_dictator_speech_v1_common_proto_rawDescData []byte
)

func file_dictator_speech_v1_common_proto_rawDescGZIP() []byte {
	file_dictator_speech_v1_common_proto_rawDescOnce.Do(func() {
		file_dictator_speech_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_common_proto_rawDesc), len(file_dictator_speech_v1_common_proto_rawDesc)))
	})
	return file_dictator_speech_v1_common_proto_rawDescData
}

var file_dictator_speech_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dictator_speech_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dictator_speech_v1_common_proto_goTypes = []any{
	(AudioContainer)(0),     // 0: dictator.speech.v1.AudioContainer
	(AudioCodec)(0),         // 1: dictator.speech.v1.AudioCodec
	(*ArtifactRef)(nil),     // 2: dictator.speech.v1.ArtifactRef
	(*AudioFormat)(nil),     // 3: dictator.speech.v1.AudioFormat
	(*AudioMetadata)(nil),   // 4: dictator.speech.v1.AudioMetadata
	(*WordSegment)(nil),     // 5: dictator.speech.v1.WordSegment
	(*TimelineSegment)(nil), // 6: dictator.speech.v1.TimelineSegment
}
var file_dictator_speech_v1_common_proto_depIdxs = []int32{
	4, // 0: dictator.speech.v1.ArtifactRef.audio_metadata:type_name -> dictator.speech.v1.AudioMetadata
	0, // 1: dictator.speech.v1.AudioFormat.container:type_name -> dictator.speech.v1.AudioContainer
	1, // 2: dictator.speech.v1.AudioFormat.codec:type_name -> dictator.speech.v1.AudioCodec
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dictator_speech_v1_common_proto_init() }
func file_dictator_speech_v1_common_proto_init() {
	if File_dictator_speech_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_common_proto_rawDesc), len(file_dictator_speech_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictator_speech_v1_common_proto_goTypes,
		DependencyIndexes: file_dictator_speech_v1_common_proto_depIdxs,
		EnumInfos:         file_dictator_speech_v1_common_proto_enumTypes,
		MessageInfos:      file_dictator_speech_v1_common_proto_msgTypes,
	}.Build()
	File_dictator_speech_v1_common_proto = out.File
	file_dictator_speech_v1_common_proto_goTypes = nil
	file_dictator_speech_v1_common_proto_depIdxs = nil
}
