// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: dictator/speech/v1/common.proto

package dictatorspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_dictator_speech_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRef) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactRef) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ArtifactRef) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ArtifactRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type WordSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	StartSeconds  float64                `protobuf:"fixed64,2,opt,name=start_seconds,json=startSeconds,proto3" json:"start_seconds,omitempty"`
	EndSeconds    float64                `protobuf:"fixed64,3,opt,name=end_seconds,json=endSeconds,proto3" json:"end_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordSegment) Reset() {
	*x = WordSegment{}
	mi := &file_dictator_speech_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordSegment) ProtoMessage() {}

func (x *WordSegment) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordSegment.ProtoReflect.Descriptor instead.
func (*WordSegment) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *WordSegment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WordSegment) GetStartSeconds() float64 {
	if x != nil {
		return x.StartSeconds
	}
	return 0
}

func (x *WordSegment) GetEndSeconds() float64 {
	if x != nil {
		return x.EndSeconds
	}
	return 0
}

type TimelineSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	StartSeconds  float64                `protobuf:"fixed64,2,opt,name=start_seconds,json=startSeconds,proto3" json:"start_seconds,omitempty"`
	EndSeconds    float64                `protobuf:"fixed64,3,opt,name=end_seconds,json=endSeconds,proto3" json:"end_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineSegment) Reset() {
	*x = TimelineSegment{}
	mi := &file_dictator_speech_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineSegment) ProtoMessage() {}

func (x *TimelineSegment) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineSegment.ProtoReflect.Descriptor instead.
func (*TimelineSegment) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *TimelineSegment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TimelineSegment) GetStartSeconds() float64 {
	if x != nil {
		return x.StartSeconds
	}
	return 0
}

func (x *TimelineSegment) GetEndSeconds() float64 {
	if x != nil {
		return x.EndSeconds
	}
	return 0
}

var File_dictator_speech_v1_common_proto protoreflect.FileDescriptor

const file_dictator_speech_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1fdictator/speech/v1/common.proto\x12\x12dictator.speech.v1\"\xa0\x01\n" +
	"\vArtifactRef\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\"m\n" +
	"\vWordSegment\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\rstart_seconds\x18\x02 \x01(\x01R\fstartSeconds\x12\x1f\n" +
	"\vend_seconds\x18\x03 \x01(\x01R\n" +
	"endSeconds\"q\n" +
	"\x0fTimelineSegment\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\rstart_seconds\x18\x02 \x01(\x01R\fstartSeconds\x12\x1f\n" +
	"\vend_seconds\x18\x03 \x01(\x01R\n" +
	"endSecondsBGZEgithub.com/tyemirov/dictator/sdk/go/dictatorspeechv1;dictatorspeechv1b\x06proto3"

var (
	file_dictator_speech_v1_common_proto_rawDescOnce sync.Once
	file_dictator_speech_v1_common_proto_rawDescData []byte
)

func file_dictator_speech_v1_common_proto_rawDescGZIP() []byte {
	file_dictator_speech_v1_common_proto_rawDescOnce.Do(func() {
		file_dictator_speech_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_common_proto_rawDesc), len(file_dictator_speech_v1_common_proto_rawDesc)))
	})
	return file_dictator_speech_v1_common_proto_rawDescData
}

var file_dictator_speech_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dictator_speech_v1_common_proto_goTypes = []any{
	(*ArtifactRef)(nil),     // 0: dictator.speech.v1.ArtifactRef
	(*WordSegment)(nil),     // 1: dictator.speech.v1.WordSegment
	(*TimelineSegment)(nil), // 2: dictator.speech.v1.TimelineSegment
}
var file_dictator_speech_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictator_speech_v1_common_proto_init() }
func file_dictator_speech_v1_common_proto_init() {
	if File_dictator_speech_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_common_proto_rawDesc), len(file_dictator_speech_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictator_speech_v1_common_proto_goTypes,
		DependencyIndexes: file_dictator_speech_v1_common_proto_depIdxs,
		MessageInfos:      file_dictator_speech_v1_common_proto_msgTypes,
	}.Build()
	File_dictator_speech_v1_common_proto = out.File
	file_dictator_speech_v1_common_proto_goTypes = nil
	file_dictator_speech_v1_common_proto_depIdxs = nil
}
