// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: dictator/speech/v1/runtime.proto

package dictatorspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_dictator_speech_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type GetMetricsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestsTotal         int64                  `protobuf:"varint,1,opt,name=requests_total,json=requestsTotal,proto3" json:"requests_total,omitempty"`
	RequestsSucceeded     int64                  `protobuf:"varint,2,opt,name=requests_succeeded,json=requestsSucceeded,proto3" json:"requests_succeeded,omitempty"`
	RequestsFailed        int64                  `protobuf:"varint,3,opt,name=requests_failed,json=requestsFailed,proto3" json:"requests_failed,omitempty"`
	Inflight              int64                  `protobuf:"varint,4,opt,name=inflight,proto3" json:"inflight,omitempty"`
	BytesReceived         int64                  `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	UptimeSeconds         float64                `protobuf:"fixed64,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	AverageLatencySeconds float64                `protobuf:"fixed64,7,opt,name=average_latency_seconds,json=averageLatencySeconds,proto3" json:"average_latency_seconds,omitempty"`
	MaxLatencySeconds     float64                `protobuf:"fixed64,8,opt,name=max_latency_seconds,json=maxLatencySeconds,proto3" json:"max_latency_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_dictator_speech_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricsResponse) GetRequestsTotal() int64 {
	if x != nil {
		return x.RequestsTotal
	}
	return 0
}

func (x *GetMetricsResponse) GetRequestsSucceeded() int64 {
	if x != nil {
		return x.RequestsSucceeded
	}
	return 0
}

func (x *GetMetricsResponse) GetRequestsFailed() int64 {
	if x != nil {
		return x.RequestsFailed
	}
	return 0
}

func (x *GetMetricsResponse) GetInflight() int64 {
	if x != nil {
		return x.Inflight
	}
	return 0
}

func (x *GetMetricsResponse) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *GetMetricsResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetMetricsResponse) GetAverageLatencySeconds() float64 {
	if x != nil {
		return x.AverageLatencySeconds
	}
	return 0
}

func (x *GetMetricsResponse) GetMaxLatencySeconds() float64 {
	if x != nil {
		return x.MaxLatencySeconds
	}
	return 0
}

var File_dictator_speech_v1_runtime_proto protoreflect.FileDescriptor

const file_dictator_speech_v1_runtime_proto_rawDesc = "" +
	"\n" +
	" dictator/speech/v1/runtime.proto\x12\x12dictator.speech.v1\"\x13\n" +
	"\x11GetMetricsRequest\"\xe5\x02\n" +
	"\x12GetMetricsResponse\x12%\n" +
	"\x0erequests_total\x18\x01 \x01(\x03R\rrequestsTotal\x12-\n" +
	"\x12requests_succeeded\x18\x02 \x01(\x03R\x11requestsSucceeded\x12'\n" +
	"\x0frequests_failed\x18\x03 \x01(\x03R\x0erequestsFailed\x12\x1a\n" +
	"\binflight\x18\x04 \x01(\x03R\binflight\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x03R\rbytesReceived\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x01R\ruptimeSeconds\x126\n" +
	"\x17average_latency_seconds\x18\a \x01(\x01R\x15averageLatencySeconds\x12.\n" +
	"\x13max_latency_seconds\x18\b \x01(\x01R\x11maxLatencySeconds2m\n" +
	"\x0eRuntimeService\x12[\n" +
	"\n" +
	"GetMetrics\x12%.dictator.speech.v1.GetMetricsRequest\x1a&.dictator.speech.v1.GetMetricsResponseBGZEgithub.com/tyemirov/dictator/sdk/go/dictatorspeechv1;dictatorspeechv1b\x06proto3"

var (
	file_dictator_speech_v1_runtime_proto_rawDescOnce sync.Once
	file_dictator_speech_v1_runtime_proto_rawDescData []byte
)

func file_dictator_speech_v1_runtime_proto_rawDescGZIP() []byte {
	file_dictator_speech_v1_runtime_proto_rawDescOnce.Do(func() {
		file_dictator_speech_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_runtime_proto_rawDesc), len(file_dictator_speech_v1_runtime_proto_rawDesc)))
	})
	return file_dictator_speech_v1_runtime_proto_rawDescData
}

var file_dictator_speech_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dictator_speech_v1_runtime_proto_goTypes = []any{
	(*GetMetricsRequest)(nil),  // 0: dictator.speech.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil), // 1: dictator.speech.v1.GetMetricsResponse
}
var file_dictator_speech_v1_runtime_proto_depIdxs = []int32{
	0, // 0: dictator.speech.v1.RuntimeService.GetMetrics:input_type -> dictator.speech.v1.GetMetricsRequest
	1, // 1: dictator.speech.v1.RuntimeService.GetMetrics:output_type -> dictator.speech.v1.GetMetricsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictator_speech_v1_runtime_proto_init() }
func file_dictator_speech_v1_runtime_proto_init() {
	if File_dictator_speech_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_runtime_proto_rawDesc), len(file_dictator_speech_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dictator_speech_v1_runtime_proto_goTypes,
		DependencyIndexes: file_dictator_speech_v1_runtime_proto_depIdxs,
		MessageInfos:      file_dictator_speech_v1_runtime_proto_msgTypes,
	}.Build()
	File_dictator_speech_v1_runtime_proto = out.File
	file_dictator_speech_v1_runtime_proto_goTypes = nil
	file_dictator_speech_v1_runtime_proto_depIdxs = nil
}
