// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: dictator/speech/v1/subtitle.proto

package dictatorspeechv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubtitleService_RenderSubtitles_FullMethodName          = "/dictator.speech.v1.SubtitleService/RenderSubtitles"
	SubtitleService_SubmitRenderSubtitlesJob_FullMethodName = "/dictator.speech.v1.SubtitleService/SubmitRenderSubtitlesJob"
	SubtitleService_GetRenderSubtitlesJob_FullMethodName    = "/dictator.speech.v1.SubtitleService/GetRenderSubtitlesJob"
)

// SubtitleServiceClient is the client API for SubtitleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubtitleServiceClient interface {
	RenderSubtitles(ctx context.Context, in *RenderSubtitlesRequest, opts ...grpc.CallOption) (*RenderSubtitlesResponse, error)
	SubmitRenderSubtitlesJob(ctx context.Context, in *RenderSubtitlesRequest, opts ...grpc.CallOption) (*SubmitRenderSubtitlesJobResponse, error)
	GetRenderSubtitlesJob(ctx context.Context, in *GetRenderSubtitlesJobRequest, opts ...grpc.CallOption) (*GetRenderSubtitlesJobResponse, error)
}

type subtitleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubtitleServiceClient(cc grpc.ClientConnInterface) SubtitleServiceClient {
	return &subtitleServiceClient{cc}
}

func (c *subtitleServiceClient) RenderSubtitles(ctx context.Context, in *RenderSubtitlesRequest, opts ...grpc.CallOption) (*RenderSubtitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderSubtitlesResponse)
	err := c.cc.Invoke(ctx, SubtitleService_RenderSubtitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subtitleServiceClient) SubmitRenderSubtitlesJob(ctx context.Context, in *RenderSubtitlesRequest, opts ...grpc.CallOption) (*SubmitRenderSubtitlesJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRenderSubtitlesJobResponse)
	err := c.cc.Invoke(ctx, SubtitleService_SubmitRenderSubtitlesJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subtitleServiceClient) GetRenderSubtitlesJob(ctx context.Context, in *GetRenderSubtitlesJobRequest, opts ...grpc.CallOption) (*GetRenderSubtitlesJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRenderSubtitlesJobResponse)
	err := c.cc.Invoke(ctx, SubtitleService_GetRenderSubtitlesJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubtitleServiceServer is the server API for SubtitleService service.
// All implementations must embed UnimplementedSubtitleServiceServer
// for forward compatibility.
type SubtitleServiceServer interface {
	RenderSubtitles(context.Context, *RenderSubtitlesRequest) (*RenderSubtitlesResponse, error)
	SubmitRenderSubtitlesJob(context.Context, *RenderSubtitlesRequest) (*SubmitRenderSubtitlesJobResponse, error)
	GetRenderSubtitlesJob(context.Context, *GetRenderSubtitlesJobRequest) (*GetRenderSubtitlesJobResponse, error)
	mustEmbedUnimplementedSubtitleServiceServer()
}

// UnimplementedSubtitleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubtitleServiceServer struct{}

func (UnimplementedSubtitleServiceServer) RenderSubtitles(context.Context, *RenderSubtitlesRequest) (*RenderSubtitlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderSubtitles not implemented")
}
func (UnimplementedSubtitleServiceServer) SubmitRenderSubtitlesJob(context.Context, *RenderSubtitlesRequest) (*SubmitRenderSubtitlesJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRenderSubtitlesJob not implemented")
}
func (UnimplementedSubtitleServiceServer) GetRenderSubtitlesJob(context.Context, *GetRenderSubtitlesJobRequest) (*GetRenderSubtitlesJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRenderSubtitlesJob not implemented")
}
func (UnimplementedSubtitleServiceServer) mustEmbedUnimplementedSubtitleServiceServer() {}
func (UnimplementedSubtitleServiceServer) testEmbeddedByValue()                         {}

// UnsafeSubtitleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubtitleServiceServer will
// result in compilation errors.
type UnsafeSubtitleServiceServer interface {
	mustEmbedUnimplementedSubtitleServiceServer()
}

func RegisterSubtitleServiceServer(s grpc.ServiceRegistrar, srv SubtitleServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubtitleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubtitleService_ServiceDesc, srv)
}

func _SubtitleService_RenderSubtitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderSubtitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtitleServiceServer).RenderSubtitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubtitleService_RenderSubtitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtitleServiceServer).RenderSubtitles(ctx, req.(*RenderSubtitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubtitleService_SubmitRenderSubtitlesJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderSubtitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtitleServiceServer).SubmitRenderSubtitlesJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubtitleService_SubmitRenderSubtitlesJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtitleServiceServer).SubmitRenderSubtitlesJob(ctx, req.(*RenderSubtitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubtitleService_GetRenderSubtitlesJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRenderSubtitlesJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtitleServiceServer).GetRenderSubtitlesJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubtitleService_GetRenderSubtitlesJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtitleServiceServer).GetRenderSubtitlesJob(ctx, req.(*GetRenderSubtitlesJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubtitleService_ServiceDesc is the grpc.ServiceDesc for SubtitleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubtitleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dictator.speech.v1.SubtitleService",
	HandlerType: (*SubtitleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderSubtitles",
			Handler:    _SubtitleService_RenderSubtitles_Handler,
		},
		{
			MethodName: "SubmitRenderSubtitlesJob",
			Handler:    _SubtitleService_SubmitRenderSubtitlesJob_Handler,
		},
		{
			MethodName: "GetRenderSubtitlesJob",
			Handler:    _SubtitleService_GetRenderSubtitlesJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dictator/speech/v1/subtitle.proto",
}
