// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: dictator/speech/v1/subtitle.proto

package dictatorspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubtitleJobState int32

const (
	SubtitleJobState_SUBTITLE_JOB_STATE_UNSPECIFIED SubtitleJobState = 0
	SubtitleJobState_SUBTITLE_JOB_STATE_QUEUED      SubtitleJobState = 1
	SubtitleJobState_SUBTITLE_JOB_STATE_RUNNING     SubtitleJobState = 2
	SubtitleJobState_SUBTITLE_JOB_STATE_SUCCEEDED   SubtitleJobState = 3
	SubtitleJobState_SUBTITLE_JOB_STATE_FAILED      SubtitleJobState = 4
	SubtitleJobState_SUBTITLE_JOB_STATE_CANCELED    SubtitleJobState = 5
)

// Enum value maps for SubtitleJobState.
var (
	SubtitleJobState_name = map[int32]string{
		0: "SUBTITLE_JOB_STATE_UNSPECIFIED",
		1: "SUBTITLE_JOB_STATE_QUEUED",
		2: "SUBTITLE_JOB_STATE_RUNNING",
		3: "SUBTITLE_JOB_STATE_SUCCEEDED",
		4: "SUBTITLE_JOB_STATE_FAILED",
		5: "SUBTITLE_JOB_STATE_CANCELED",
	}
	SubtitleJobState_value = map[string]int32{
		"SUBTITLE_JOB_STATE_UNSPECIFIED": 0,
		"SUBTITLE_JOB_STATE_QUEUED":      1,
		"SUBTITLE_JOB_STATE_RUNNING":     2,
		"SUBTITLE_JOB_STATE_SUCCEEDED":   3,
		"SUBTITLE_JOB_STATE_FAILED":      4,
		"SUBTITLE_JOB_STATE_CANCELED":    5,
	}
)

func (x SubtitleJobState) Enum() *SubtitleJobState {
	p := new(SubtitleJobState)
	*p = x
	return p
}

func (x SubtitleJobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubtitleJobState) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_subtitle_proto_enumTypes[0].Descriptor()
}

func (SubtitleJobState) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_subtitle_proto_enumTypes[0]
}

func (x SubtitleJobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubtitleJobState.Descriptor instead.
func (SubtitleJobState) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{0}
}

type SubtitleFormat int32

const (
	SubtitleFormat_SUBTITLE_FORMAT_UNSPECIFIED SubtitleFormat = 0
	SubtitleFormat_SUBTITLE_FORMAT_SRT         SubtitleFormat = 1
)

// Enum value maps for SubtitleFormat.
var (
	SubtitleFormat_name = map[int32]string{
		0: "SUBTITLE_FORMAT_UNSPECIFIED",
		1: "SUBTITLE_FORMAT_SRT",
	}
	SubtitleFormat_value = map[string]int32{
		"SUBTITLE_FORMAT_UNSPECIFIED": 0,
		"SUBTITLE_FORMAT_SRT":         1,
	}
)

func (x SubtitleFormat) Enum() *SubtitleFormat {
	p := new(SubtitleFormat)
	*p = x
	return p
}

func (x SubtitleFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubtitleFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_subtitle_proto_enumTypes[1].Descriptor()
}

func (SubtitleFormat) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_subtitle_proto_enumTypes[1]
}

func (x SubtitleFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubtitleFormat.Descriptor instead.
func (SubtitleFormat) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{1}
}

type SubtitleGranularity int32

const (
	SubtitleGranularity_SUBTITLE_GRANULARITY_UNSPECIFIED SubtitleGranularity = 0
	SubtitleGranularity_SUBTITLE_GRANULARITY_WORDS       SubtitleGranularity = 1
	SubtitleGranularity_SUBTITLE_GRANULARITY_SENTENCES   SubtitleGranularity = 2
)

// Enum value maps for SubtitleGranularity.
var (
	SubtitleGranularity_name = map[int32]string{
		0: "SUBTITLE_GRANULARITY_UNSPECIFIED",
		1: "SUBTITLE_GRANULARITY_WORDS",
		2: "SUBTITLE_GRANULARITY_SENTENCES",
	}
	SubtitleGranularity_value = map[string]int32{
		"SUBTITLE_GRANULARITY_UNSPECIFIED": 0,
		"SUBTITLE_GRANULARITY_WORDS":       1,
		"SUBTITLE_GRANULARITY_SENTENCES":   2,
	}
)

func (x SubtitleGranularity) Enum() *SubtitleGranularity {
	p := new(SubtitleGranularity)
	*p = x
	return p
}

func (x SubtitleGranularity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubtitleGranularity) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_subtitle_proto_enumTypes[2].Descriptor()
}

func (SubtitleGranularity) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_subtitle_proto_enumTypes[2]
}

func (x SubtitleGranularity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubtitleGranularity.Descriptor instead.
func (SubtitleGranularity) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{2}
}

type SubtitleMode int32

const (
	SubtitleMode_SUBTITLE_MODE_UNSPECIFIED      SubtitleMode = 0
	SubtitleMode_SUBTITLE_MODE_TRANSCRIPTION    SubtitleMode = 1
	SubtitleMode_SUBTITLE_MODE_FORCED_ALIGNMENT SubtitleMode = 2
)

// Enum value maps for SubtitleMode.
var (
	SubtitleMode_name = map[int32]string{
		0: "SUBTITLE_MODE_UNSPECIFIED",
		1: "SUBTITLE_MODE_TRANSCRIPTION",
		2: "SUBTITLE_MODE_FORCED_ALIGNMENT",
	}
	SubtitleMode_value = map[string]int32{
		"SUBTITLE_MODE_UNSPECIFIED":      0,
		"SUBTITLE_MODE_TRANSCRIPTION":    1,
		"SUBTITLE_MODE_FORCED_ALIGNMENT": 2,
	}
)

func (x SubtitleMode) Enum() *SubtitleMode {
	p := new(SubtitleMode)
	*p = x
	return p
}

func (x SubtitleMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubtitleMode) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_subtitle_proto_enumTypes[3].Descriptor()
}

func (SubtitleMode) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_subtitle_proto_enumTypes[3]
}

func (x SubtitleMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubtitleMode.Descriptor instead.
func (SubtitleMode) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{3}
}

type SubtitleCue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	StartSeconds  float64                `protobuf:"fixed64,2,opt,name=start_seconds,json=startSeconds,proto3" json:"start_seconds,omitempty"`
	EndSeconds    float64                `protobuf:"fixed64,3,opt,name=end_seconds,json=endSeconds,proto3" json:"end_seconds,omitempty"`
	ItemCount     int32                  `protobuf:"varint,4,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtitleCue) Reset() {
	*x = SubtitleCue{}
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitleCue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitleCue) ProtoMessage() {}

func (x *SubtitleCue) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitleCue.ProtoReflect.Descriptor instead.
func (*SubtitleCue) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{0}
}

func (x *SubtitleCue) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubtitleCue) GetStartSeconds() float64 {
	if x != nil {
		return x.StartSeconds
	}
	return 0
}

func (x *SubtitleCue) GetEndSeconds() float64 {
	if x != nil {
		return x.EndSeconds
	}
	return 0
}

func (x *SubtitleCue) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

type RenderSubtitlesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AudioArtifactId    string                 `protobuf:"bytes,1,opt,name=audio_artifact_id,json=audioArtifactId,proto3" json:"audio_artifact_id,omitempty"`
	LanguageCode       string                 `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	AutodetectLanguage bool                   `protobuf:"varint,3,opt,name=autodetect_language,json=autodetectLanguage,proto3" json:"autodetect_language,omitempty"`
	ModelSize          string                 `protobuf:"bytes,4,opt,name=model_size,json=modelSize,proto3" json:"model_size,omitempty"`
	OutputFormat       SubtitleFormat         `protobuf:"varint,5,opt,name=output_format,json=outputFormat,proto3,enum=dictator.speech.v1.SubtitleFormat" json:"output_format,omitempty"`
	Granularity        SubtitleGranularity    `protobuf:"varint,6,opt,name=granularity,proto3,enum=dictator.speech.v1.SubtitleGranularity" json:"granularity,omitempty"`
	GroupSize          int32                  `protobuf:"varint,7,opt,name=group_size,json=groupSize,proto3" json:"group_size,omitempty"`
	// Types that are valid to be assigned to SourceTextSource:
	//
	//	*RenderSubtitlesRequest_SourceText
	//	*RenderSubtitlesRequest_SourceTextArtifactId
	SourceTextSource isRenderSubtitlesRequest_SourceTextSource `protobuf_oneof:"source_text_source"`
	SourceTextName   string                                    `protobuf:"bytes,10,opt,name=source_text_name,json=sourceTextName,proto3" json:"source_text_name,omitempty"`
	IncludeSrtText   bool                                      `protobuf:"varint,11,opt,name=include_srt_text,json=includeSrtText,proto3" json:"include_srt_text,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RenderSubtitlesRequest) Reset() {
	*x = RenderSubtitlesRequest{}
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSubtitlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSubtitlesRequest) ProtoMessage() {}

func (x *RenderSubtitlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSubtitlesRequest.ProtoReflect.Descriptor instead.
func (*RenderSubtitlesRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{1}
}

func (x *RenderSubtitlesRequest) GetAudioArtifactId() string {
	if x != nil {
		return x.AudioArtifactId
	}
	return ""
}

func (x *RenderSubtitlesRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *RenderSubtitlesRequest) GetAutodetectLanguage() bool {
	if x != nil {
		return x.AutodetectLanguage
	}
	return false
}

func (x *RenderSubtitlesRequest) GetModelSize() string {
	if x != nil {
		return x.ModelSize
	}
	return ""
}

func (x *RenderSubtitlesRequest) GetOutputFormat() SubtitleFormat {
	if x != nil {
		return x.OutputFormat
	}
	return SubtitleFormat_SUBTITLE_FORMAT_UNSPECIFIED
}

func (x *RenderSubtitlesRequest) GetGranularity() SubtitleGranularity {
	if x != nil {
		return x.Granularity
	}
	return SubtitleGranularity_SUBTITLE_GRANULARITY_UNSPECIFIED
}

func (x *RenderSubtitlesRequest) GetGroupSize() int32 {
	if x != nil {
		return x.GroupSize
	}
	return 0
}

func (x *RenderSubtitlesRequest) GetSourceTextSource() isRenderSubtitlesRequest_SourceTextSource {
	if x != nil {
		return x.SourceTextSource
	}
	return nil
}

func (x *RenderSubtitlesRequest) GetSourceText() string {
	if x != nil {
		if x, ok := x.SourceTextSource.(*RenderSubtitlesRequest_SourceText); ok {
			return x.SourceText
		}
	}
	return ""
}

func (x *RenderSubtitlesRequest) GetSourceTextArtifactId() string {
	if x != nil {
		if x, ok := x.SourceTextSource.(*RenderSubtitlesRequest_SourceTextArtifactId); ok {
			return x.SourceTextArtifactId
		}
	}
	return ""
}

func (x *RenderSubtitlesRequest) GetSourceTextName() string {
	if x != nil {
		return x.SourceTextName
	}
	return ""
}

func (x *RenderSubtitlesRequest) GetIncludeSrtText() bool {
	if x != nil {
		return x.IncludeSrtText
	}
	return false
}

type isRenderSubtitlesRequest_SourceTextSource interface {
	isRenderSubtitlesRequest_SourceTextSource()
}

type RenderSubtitlesRequest_SourceText struct {
	SourceText string `protobuf:"bytes,8,opt,name=source_text,json=sourceText,proto3,oneof"`
}

type RenderSubtitlesRequest_SourceTextArtifactId struct {
	SourceTextArtifactId string `protobuf:"bytes,9,opt,name=source_text_artifact_id,json=sourceTextArtifactId,proto3,oneof"`
}

func (*RenderSubtitlesRequest_SourceText) isRenderSubtitlesRequest_SourceTextSource() {}

func (*RenderSubtitlesRequest_SourceTextArtifactId) isRenderSubtitlesRequest_SourceTextSource() {}

type RenderSubtitlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LanguageCode  string                 `protobuf:"bytes,1,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	Mode          SubtitleMode           `protobuf:"varint,2,opt,name=mode,proto3,enum=dictator.speech.v1.SubtitleMode" json:"mode,omitempty"`
	OutputFormat  SubtitleFormat         `protobuf:"varint,3,opt,name=output_format,json=outputFormat,proto3,enum=dictator.speech.v1.SubtitleFormat" json:"output_format,omitempty"`
	Granularity   SubtitleGranularity    `protobuf:"varint,4,opt,name=granularity,proto3,enum=dictator.speech.v1.SubtitleGranularity" json:"granularity,omitempty"`
	GroupSize     int32                  `protobuf:"varint,5,opt,name=group_size,json=groupSize,proto3" json:"group_size,omitempty"`
	Cues          []*SubtitleCue         `protobuf:"bytes,6,rep,name=cues,proto3" json:"cues,omitempty"`
	SrtText       string                 `protobuf:"bytes,7,opt,name=srt_text,json=srtText,proto3" json:"srt_text,omitempty"`
	SrtArtifactId string                 `protobuf:"bytes,8,opt,name=srt_artifact_id,json=srtArtifactId,proto3" json:"srt_artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderSubtitlesResponse) Reset() {
	*x = RenderSubtitlesResponse{}
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSubtitlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSubtitlesResponse) ProtoMessage() {}

func (x *RenderSubtitlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSubtitlesResponse.ProtoReflect.Descriptor instead.
func (*RenderSubtitlesResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{2}
}

func (x *RenderSubtitlesResponse) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *RenderSubtitlesResponse) GetMode() SubtitleMode {
	if x != nil {
		return x.Mode
	}
	return SubtitleMode_SUBTITLE_MODE_UNSPECIFIED
}

func (x *RenderSubtitlesResponse) GetOutputFormat() SubtitleFormat {
	if x != nil {
		return x.OutputFormat
	}
	return SubtitleFormat_SUBTITLE_FORMAT_UNSPECIFIED
}

func (x *RenderSubtitlesResponse) GetGranularity() SubtitleGranularity {
	if x != nil {
		return x.Granularity
	}
	return SubtitleGranularity_SUBTITLE_GRANULARITY_UNSPECIFIED
}

func (x *RenderSubtitlesResponse) GetGroupSize() int32 {
	if x != nil {
		return x.GroupSize
	}
	return 0
}

func (x *RenderSubtitlesResponse) GetCues() []*SubtitleCue {
	if x != nil {
		return x.Cues
	}
	return nil
}

func (x *RenderSubtitlesResponse) GetSrtText() string {
	if x != nil {
		return x.SrtText
	}
	return ""
}

func (x *RenderSubtitlesResponse) GetSrtArtifactId() string {
	if x != nil {
		return x.SrtArtifactId
	}
	return ""
}

type SubmitRenderSubtitlesJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         SubtitleJobState       `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.SubtitleJobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRenderSubtitlesJobResponse) Reset() {
	*x = SubmitRenderSubtitlesJobResponse{}
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRenderSubtitlesJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRenderSubtitlesJobResponse) ProtoMessage() {}

func (x *SubmitRenderSubtitlesJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRenderSubtitlesJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitRenderSubtitlesJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitRenderSubtitlesJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitRenderSubtitlesJobResponse) GetState() SubtitleJobState {
	if x != nil {
		return x.State
	}
	return SubtitleJobState_SUBTITLE_JOB_STATE_UNSPECIFIED
}

type GetRenderSubtitlesJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRenderSubtitlesJobRequest) Reset() {
	*x = GetRenderSubtitlesJobRequest{}
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRenderSubtitlesJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRenderSubtitlesJobRequest) ProtoMessage() {}

func (x *GetRenderSubtitlesJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRenderSubtitlesJobRequest.ProtoReflect.Descriptor instead.
func (*GetRenderSubtitlesJobRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{4}
}

func (x *GetRenderSubtitlesJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetRenderSubtitlesJobResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	JobId                 string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State                 SubtitleJobState       `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.SubtitleJobState" json:"state,omitempty"`
	ErrorCode             string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LanguageCode          string                 `protobuf:"bytes,5,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	Mode                  SubtitleMode           `protobuf:"varint,6,opt,name=mode,proto3,enum=dictator.speech.v1.SubtitleMode" json:"mode,omitempty"`
	OutputFormat          SubtitleFormat         `protobuf:"varint,7,opt,name=output_format,json=outputFormat,proto3,enum=dictator.speech.v1.SubtitleFormat" json:"output_format,omitempty"`
	Granularity           SubtitleGranularity    `protobuf:"varint,8,opt,name=granularity,proto3,enum=dictator.speech.v1.SubtitleGranularity" json:"granularity,omitempty"`
	GroupSize             int32                  `protobuf:"varint,9,opt,name=group_size,json=groupSize,proto3" json:"group_size,omitempty"`
	Cues                  []*SubtitleCue         `protobuf:"bytes,10,rep,name=cues,proto3" json:"cues,omitempty"`
	SrtText               string                 `protobuf:"bytes,11,opt,name=srt_text,json=srtText,proto3" json:"srt_text,omitempty"`
	SrtArtifactId         string                 `protobuf:"bytes,12,opt,name=srt_artifact_id,json=srtArtifactId,proto3" json:"srt_artifact_id,omitempty"`
	CreatedAtUnixSeconds  float64                `protobuf:"fixed64,13,opt,name=created_at_unix_seconds,json=createdAtUnixSeconds,proto3" json:"created_at_unix_seconds,omitempty"`
	StartedAtUnixSeconds  float64                `protobuf:"fixed64,14,opt,name=started_at_unix_seconds,json=startedAtUnixSeconds,proto3" json:"started_at_unix_seconds,omitempty"`
	FinishedAtUnixSeconds float64                `protobuf:"fixed64,15,opt,name=finished_at_unix_seconds,json=finishedAtUnixSeconds,proto3" json:"finished_at_unix_seconds,omitempty"`
	SourceArtifactId      string                 `protobuf:"bytes,16,opt,name=source_artifact_id,json=sourceArtifactId,proto3" json:"source_artifact_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetRenderSubtitlesJobResponse) Reset() {
	*x = GetRenderSubtitlesJobResponse{}
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRenderSubtitlesJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRenderSubtitlesJobResponse) ProtoMessage() {}

func (x *GetRenderSubtitlesJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRenderSubtitlesJobResponse.ProtoReflect.Descriptor instead.
func (*GetRenderSubtitlesJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{5}
}

func (x *GetRenderSubtitlesJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetRenderSubtitlesJobResponse) GetState() SubtitleJobState {
	if x != nil {
		return x.State
	}
	return SubtitleJobState_SUBTITLE_JOB_STATE_UNSPECIFIED
}

func (x *GetRenderSubtitlesJobResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetRenderSubtitlesJobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetRenderSubtitlesJobResponse) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *GetRenderSubtitlesJobResponse) GetMode() SubtitleMode {
	if x != nil {
		return x.Mode
	}
	return SubtitleMode_SUBTITLE_MODE_UNSPECIFIED
}

func (x *GetRenderSubtitlesJobResponse) GetOutputFormat() SubtitleFormat {
	if x != nil {
		return x.OutputFormat
	}
	return SubtitleFormat_SUBTITLE_FORMAT_UNSPECIFIED
}

func (x *GetRenderSubtitlesJobResponse) GetGranularity() SubtitleGranularity {
	if x != nil {
		return x.Granularity
	}
	return SubtitleGranularity_SUBTITLE_GRANULARITY_UNSPECIFIED
}

func (x *GetRenderSubtitlesJobResponse) GetGroupSize() int32 {
	if x != nil {
		return x.GroupSize
	}
	return 0
}

func (x *GetRenderSubtitlesJobResponse) GetCues() []*SubtitleCue {
	if x != nil {
		return x.Cues
	}
	return nil
}

func (x *GetRenderSubtitlesJobResponse) GetSrtText() string {
	if x != nil {
		return x.SrtText
	}
	return ""
}

func (x *GetRenderSubtitlesJobResponse) GetSrtArtifactId() string {
	if x != nil {
		return x.SrtArtifactId
	}
	return ""
}

func (x *GetRenderSubtitlesJobResponse) GetCreatedAtUnixSeconds() float64 {
	if x != nil {
		return x.CreatedAtUnixSeconds
	}
	return 0
}

func (x *GetRenderSubtitlesJobResponse) GetStartedAtUnixSeconds() float64 {
	if x != nil {
		return x.StartedAtUnixSeconds
	}
	return 0
}

func (x *GetRenderSubtitlesJobResponse) GetFinishedAtUnixSeconds() float64 {
	if x != nil {
		return x.FinishedAtUnixSeconds
	}
	return 0
}

func (x *GetRenderSubtitlesJobResponse) GetSourceArtifactId() string {
	if x != nil {
		return x.SourceArtifactId
	}
	return ""
}

type CancelRenderSubtitlesJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRenderSubtitlesJobRequest) Reset() {
	*x = CancelRenderSubtitlesJobRequest{}
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRenderSubtitlesJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRenderSubtitlesJobRequest) ProtoMessage() {}

func (x *CancelRenderSubtitlesJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRenderSubtitlesJobRequest.ProtoReflect.Descriptor instead.
func (*CancelRenderSubtitlesJobRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRenderSubtitlesJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelRenderSubtitlesJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         SubtitleJobState       `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.SubtitleJobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRenderSubtitlesJobResponse) Reset() {
	*x = CancelRenderSubtitlesJobResponse{}
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRenderSubtitlesJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRenderSubtitlesJobResponse) ProtoMessage() {}

func (x *CancelRenderSubtitlesJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_subtitle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRenderSubtitlesJobResponse.ProtoReflect.Descriptor instead.
func (*CancelRenderSubtitlesJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_subtitle_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRenderSubtitlesJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelRenderSubtitlesJobResponse) GetState() SubtitleJobState {
	if x != nil {
		return x.State
	}
	return SubtitleJobState_SUBTITLE_JOB_STATE_UNSPECIFIED
}

var File_dictator_speech_v1_subtitle_proto protoreflect.FileDescriptor

const file_dictator_speech_v1_subtitle_proto_rawDesc = "" +
	"\n" +
	"!dictator/speech/v1/subtitle.proto\x12\x12dictator.speech.v1\"\x8c\x01\n" +
	"\vSubtitleCue\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\rstart_seconds\x18\x02 \x01(\x01R\fstartSeconds\x12\x1f\n" +
	"\vend_seconds\x18\x03 \x01(\x01R\n" +
	"endSeconds\x12\x1d\n" +
	"\n" +
	"item_count\x18\x04 \x01(\x05R\titemCount\"\xb2\x04\n" +
	"\x16RenderSubtitlesRequest\x12*\n" +
	"\x11audio_artifact_id\x18\x01 \x01(\tR\x0faudioArtifactId\x12#\n" +
	"\rlanguage_code\x18\x02 \x01(\tR\flanguageCode\x12/\n" +
	"\x13autodetect_language\x18\x03 \x01(\bR\x12autodetectLanguage\x12\x1d\n" +
	"\n" +
	"model_size\x18\x04 \x01(\tR\tmodelSize\x12G\n" +
	"\routput_format\x18\x05 \x01(\x0e2\".dictator.speech.v1.SubtitleFormatR\foutputFormat\x12I\n" +
	"\vgranularity\x18\x06 \x01(\x0e2'.dictator.speech.v1.SubtitleGranularityR\vgranularity\x12\x1d\n" +
	"\n" +
	"group_size\x18\a \x01(\x05R\tgroupSize\x12!\n" +
	"\vsource_text\x18\b \x01(\tH\x00R\n" +
	"sourceText\x127\n" +
	"\x17source_text_artifact_id\x18\t \x01(\tH\x00R\x14sourceTextArtifactId\x12(\n" +
	"\x10source_text_name\x18\n" +
	" \x01(\tR\x0esourceTextName\x12(\n" +
	"\x10include_srt_text\x18\v \x01(\bR\x0eincludeSrtTextB\x14\n" +
	"\x12source_text_source\"\x9f\x03\n" +
	"\x17RenderSubtitlesResponse\x12#\n" +
	"\rlanguage_code\x18\x01 \x01(\tR\flanguageCode\x124\n" +
	"\x04mode\x18\x02 \x01(\x0e2 .dictator.speech.v1.SubtitleModeR\x04mode\x12G\n" +
	"\routput_format\x18\x03 \x01(\x0e2\".dictator.speech.v1.SubtitleFormatR\foutputFormat\x12I\n" +
	"\vgranularity\x18\x04 \x01(\x0e2'.dictator.speech.v1.SubtitleGranularityR\vgranularity\x12\x1d\n" +
	"\n" +
	"group_size\x18\x05 \x01(\x05R\tgroupSize\x123\n" +
	"\x04cues\x18\x06 \x03(\v2\x1f.dictator.speech.v1.SubtitleCueR\x04cues\x12\x19\n" +
	"\bsrt_text\x18\a \x01(\tR\asrtText\x12&\n" +
	"\x0fsrt_artifact_id\x18\b \x01(\tR\rsrtArtifactId\"u\n" +
	" SubmitRenderSubtitlesJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12:\n" +
	"\x05state\x18\x02 \x01(\x0e2$.dictator.speech.v1.SubtitleJobStateR\x05state\"5\n" +
	"\x1cGetRenderSubtitlesJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x91\x06\n" +
	"\x1dGetRenderSubtitlesJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12:\n" +
	"\x05state\x18\x02 \x01(\x0e2$.dictator.speech.v1.SubtitleJobStateR\x05state\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12#\n" +
	"\rlanguage_code\x18\x05 \x01(\tR\flanguageCode\x124\n" +
	"\x04mode\x18\x06 \x01(\x0e2 .dictator.speech.v1.SubtitleModeR\x04mode\x12G\n" +
	"\routput_format\x18\a \x01(\x0e2\".dictator.speech.v1.SubtitleFormatR\foutputFormat\x12I\n" +
	"\vgranularity\x18\b \x01(\x0e2'.dictator.speech.v1.SubtitleGranularityR\vgranularity\x12\x1d\n" +
	"\n" +
	"group_size\x18\t \x01(\x05R\tgroupSize\x123\n" +
	"\x04cues\x18\n" +
	" \x03(\v2\x1f.dictator.speech.v1.SubtitleCueR\x04cues\x12\x19\n" +
	"\bsrt_text\x18\v \x01(\tR\asrtText\x12&\n" +
	"\x0fsrt_artifact_id\x18\f \x01(\tR\rsrtArtifactId\x125\n" +
	"\x17created_at_unix_seconds\x18\r \x01(\x01R\x14createdAtUnixSeconds\x125\n" +
	"\x17started_at_unix_seconds\x18\x0e \x01(\x01R\x14startedAtUnixSeconds\x127\n" +
	"\x18finished_at_unix_seconds\x18\x0f \x01(\x01R\x15finishedAtUnixSeconds\x12,\n" +
	"\x12source_artifact_id\x18\x10 \x01(\tR\x10sourceArtifactId\"8\n" +
	"\x1fCancelRenderSubtitlesJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"u\n" +
	" CancelRenderSubtitlesJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12:\n" +
	"\x05state\x18\x02 \x01(\x0e2$.dictator.speech.v1.SubtitleJobStateR\x05state*\xd7\x01\n" +
	"\x10SubtitleJobState\x12\"\n" +
	"\x1eSUBTITLE_JOB_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SUBTITLE_JOB_STATE_QUEUED\x10\x01\x12\x1e\n" +
	"\x1aSUBTITLE_JOB_STATE_RUNNING\x10\x02\x12 \n" +
	"\x1cSUBTITLE_JOB_STATE_SUCCEEDED\x10\x03\x12\x1d\n" +
	"\x19SUBTITLE_JOB_STATE_FAILED\x10\x04\x12\x1f\n" +
	"\x1bSUBTITLE_JOB_STATE_CANCELED\x10\x05*J\n" +
	"\x0eSubtitleFormat\x12\x1f\n" +
	"\x1bSUBTITLE_FORMAT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SUBTITLE_FORMAT_SRT\x10\x01*\x7f\n" +
	"\x13SubtitleGranularity\x12$\n" +
	" SUBTITLE_GRANULARITY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSUBTITLE_GRANULARITY_WORDS\x10\x01\x12\"\n" +
	"\x1eSUBTITLE_GRANULARITY_SENTENCES\x10\x02*r\n" +
	"\fSubtitleMode\x12\x1d\n" +
	"\x19SUBTITLE_MODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSUBTITLE_MODE_TRANSCRIPTION\x10\x01\x12\"\n" +
	"\x1eSUBTITLE_MODE_FORCED_ALIGNMENT\x10\x022\x81\x04\n" +
	"\x0fSubtitleService\x12j\n" +
	"\x0fRenderSubtitles\x12*.dictator.speech.v1.RenderSubtitlesRequest\x1a+.dictator.speech.v1.RenderSubtitlesResponse\x12|\n" +
	"\x18SubmitRenderSubtitlesJob\x12*.dictator.speech.v1.RenderSubtitlesRequest\x1a4.dictator.speech.v1.SubmitRenderSubtitlesJobResponse\x12|\n" +
	"\x15GetRenderSubtitlesJob\x120.dictator.speech.v1.GetRenderSubtitlesJobRequest\x1a1.dictator.speech.v1.GetRenderSubtitlesJobResponse\x12\x85\x01\n" +
	"\x18CancelRenderSubtitlesJob\x123.dictator.speech.v1.CancelRenderSubtitlesJobRequest\x1a4.dictator.speech.v1.CancelRenderSubtitlesJobResponseBGZEgithub.com/tyemirov/dictator/sdk/go/dictatorspeechv1;dictatorspeechv1b\x06proto3"

var (
	file_dictator_speech_v1_subtitle_proto_rawDescOnce sync.Once
	file_dictator_speech_v1_subtitle_proto_rawDescData []byte
)

func file_dictator_speech_v1_subtitle_proto_rawDescGZIP() []byte {
	file_dictator_speech_v1_subtitle_proto_rawDescOnce.Do(func() {
		file_dictator_speech_v1_subtitle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_subtitle_proto_rawDesc), len(file_dictator_speech_v1_subtitle_proto_rawDesc)))
	})
	return file_dictator_speech_v1_subtitle_proto_rawDescData
}

var file_dictator_speech_v1_subtitle_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_dictator_speech_v1_subtitle_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_dictator_speech_v1_subtitle_proto_goTypes = []any{
	(SubtitleJobState)(0),                    // 0: dictator.speech.v1.SubtitleJobState
	(SubtitleFormat)(0),                      // 1: dictator.speech.v1.SubtitleFormat
	(SubtitleGranularity)(0),                 // 2: dictator.speech.v1.SubtitleGranularity
	(SubtitleMode)(0),                        // 3: dictator.speech.v1.SubtitleMode
	(*SubtitleCue)(nil),                      // 4: dictator.speech.v1.SubtitleCue
	(*RenderSubtitlesRequest)(nil),           // 5: dictator.speech.v1.RenderSubtitlesRequest
	(*RenderSubtitlesResponse)(nil),          // 6: dictator.speech.v1.RenderSubtitlesResponse
	(*SubmitRenderSubtitlesJobResponse)(nil), // 7: dictator.speech.v1.SubmitRenderSubtitlesJobResponse
	(*GetRenderSubtitlesJobRequest)(nil),     // 8: dictator.speech.v1.GetRenderSubtitlesJobRequest
	(*GetRenderSubtitlesJobResponse)(nil),    // 9: dictator.speech.v1.GetRenderSubtitlesJobResponse
	(*CancelRenderSubtitlesJobRequest)(nil),  // 10: dictator.speech.v1.CancelRenderSubtitlesJobRequest
	(*CancelRenderSubtitlesJobResponse)(nil), // 11: dictator.speech.v1.CancelRenderSubtitlesJobResponse
}
var file_dictator_speech_v1_subtitle_proto_depIdxs = []int32{
	1,  // 0: dictator.speech.v1.RenderSubtitlesRequest.output_format:type_name -> dictator.speech.v1.SubtitleFormat
	2,  // 1: dictator.speech.v1.RenderSubtitlesRequest.granularity:type_name -> dictator.speech.v1.SubtitleGranularity
	3,  // 2: dictator.speech.v1.RenderSubtitlesResponse.mode:type_name -> dictator.speech.v1.SubtitleMode
	1,  // 3: dictator.speech.v1.RenderSubtitlesResponse.output_format:type_name -> dictator.speech.v1.SubtitleFormat
	2,  // 4: dictator.speech.v1.RenderSubtitlesResponse.granularity:type_name -> dictator.speech.v1.SubtitleGranularity
	4,  // 5: dictator.speech.v1.RenderSubtitlesResponse.cues:type_name -> dictator.speech.v1.SubtitleCue
	0,  // 6: dictator.speech.v1.SubmitRenderSubtitlesJobResponse.state:type_name -> dictator.speech.v1.SubtitleJobState
	0,  // 7: dictator.speech.v1.GetRenderSubtitlesJobResponse.state:type_name -> dictator.speech.v1.SubtitleJobState
	3,  // 8: dictator.speech.v1.GetRenderSubtitlesJobResponse.mode:type_name -> dictator.speech.v1.SubtitleMode
	1,  // 9: dictator.speech.v1.GetRenderSubtitlesJobResponse.output_format:type_name -> dictator.speech.v1.SubtitleFormat
	2,  // 10: dictator.speech.v1.GetRenderSubtitlesJobResponse.granularity:type_name -> dictator.speech.v1.SubtitleGranularity
	4,  // 11: dictator.speech.v1.GetRenderSubtitlesJobResponse.cues:type_name -> dictator.speech.v1.SubtitleCue
	0,  // 12: dictator.speech.v1.CancelRenderSubtitlesJobResponse.state:type_name -> dictator.speech.v1.SubtitleJobState
	5,  // 13: dictator.speech.v1.SubtitleService.RenderSubtitles:input_type -> dictator.speech.v1.RenderSubtitlesRequest
	5,  // 14: dictator.speech.v1.SubtitleService.SubmitRenderSubtitlesJob:input_type -> dictator.speech.v1.RenderSubtitlesRequest
	8,  // 15: dictator.speech.v1.SubtitleService.GetRenderSubtitlesJob:input_type -> dictator.speech.v1.GetRenderSubtitlesJobRequest
	10, // 16: dictator.speech.v1.SubtitleService.CancelRenderSubtitlesJob:input_type -> dictator.speech.v1.CancelRenderSubtitlesJobRequest
	6,  // 17: dictator.speech.v1.SubtitleService.RenderSubtitles:output_type -> dictator.speech.v1.RenderSubtitlesResponse
	7,  // 18: dictator.speech.v1.SubtitleService.SubmitRenderSubtitlesJob:output_type -> dictator.speech.v1.SubmitRenderSubtitlesJobResponse
	9,  // 19: dictator.speech.v1.SubtitleService.GetRenderSubtitlesJob:output_type -> dictator.speech.v1.GetRenderSubtitlesJobResponse
	11, // 20: dictator.speech.v1.SubtitleService.CancelRenderSubtitlesJob:output_type -> dictator.speech.v1.CancelRenderSubtitlesJobResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_dictator_speech_v1_subtitle_proto_init() }
func file_dictator_speech_v1_subtitle_proto_init() {
	if File_dictator_speech_v1_subtitle_proto != nil {
		return
	}
	file_dictator_speech_v1_subtitle_proto_msgTypes[1].OneofWrappers = []any{
		(*RenderSubtitlesRequest_SourceText)(nil),
		(*RenderSubtitlesRequest_SourceTextArtifactId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_subtitle_proto_rawDesc), len(file_dictator_speech_v1_subtitle_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dictator_speech_v1_subtitle_proto_goTypes,
		DependencyIndexes: file_dictator_speech_v1_subtitle_proto_depIdxs,
		EnumInfos:         file_dictator_speech_v1_subtitle_proto_enumTypes,
		MessageInfos:      file_dictator_speech_v1_subtitle_proto_msgTypes,
	}.Build()
	File_dictator_speech_v1_subtitle_proto = out.File
	file_dictator_speech_v1_subtitle_proto_goTypes = nil
	file_dictator_speech_v1_subtitle_proto_depIdxs = nil
}
