// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: dictator/speech/v1/transcription.proto

package dictatorspeechv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscriptionService_Transcribe_FullMethodName            = "/dictator.speech.v1.TranscriptionService/Transcribe"
	TranscriptionService_SubmitTranscribeJob_FullMethodName   = "/dictator.speech.v1.TranscriptionService/SubmitTranscribeJob"
	TranscriptionService_GetTranscribeJob_FullMethodName      = "/dictator.speech.v1.TranscriptionService/GetTranscribeJob"
	TranscriptionService_DiarizeAudio_FullMethodName          = "/dictator.speech.v1.TranscriptionService/DiarizeAudio"
	TranscriptionService_SubmitDiarizeAudioJob_FullMethodName = "/dictator.speech.v1.TranscriptionService/SubmitDiarizeAudioJob"
	TranscriptionService_GetDiarizeAudioJob_FullMethodName    = "/dictator.speech.v1.TranscriptionService/GetDiarizeAudioJob"
)

// TranscriptionServiceClient is the client API for TranscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscriptionServiceClient interface {
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error)
	SubmitTranscribeJob(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*SubmitTranscribeJobResponse, error)
	GetTranscribeJob(ctx context.Context, in *GetTranscribeJobRequest, opts ...grpc.CallOption) (*GetTranscribeJobResponse, error)
	DiarizeAudio(ctx context.Context, in *DiarizeAudioRequest, opts ...grpc.CallOption) (*DiarizeAudioResponse, error)
	SubmitDiarizeAudioJob(ctx context.Context, in *DiarizeAudioRequest, opts ...grpc.CallOption) (*SubmitDiarizeAudioJobResponse, error)
	GetDiarizeAudioJob(ctx context.Context, in *GetDiarizeAudioJobRequest, opts ...grpc.CallOption) (*GetDiarizeAudioJobResponse, error)
}

type transcriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscriptionServiceClient(cc grpc.ClientConnInterface) TranscriptionServiceClient {
	return &transcriptionServiceClient{cc}
}

func (c *transcriptionServiceClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcriptionServiceClient) SubmitTranscribeJob(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*SubmitTranscribeJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTranscribeJobResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_SubmitTranscribeJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcriptionServiceClient) GetTranscribeJob(ctx context.Context, in *GetTranscribeJobRequest, opts ...grpc.CallOption) (*GetTranscribeJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranscribeJobResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_GetTranscribeJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcriptionServiceClient) DiarizeAudio(ctx context.Context, in *DiarizeAudioRequest, opts ...grpc.CallOption) (*DiarizeAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiarizeAudioResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_DiarizeAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcriptionServiceClient) SubmitDiarizeAudioJob(ctx context.Context, in *DiarizeAudioRequest, opts ...grpc.CallOption) (*SubmitDiarizeAudioJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDiarizeAudioJobResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_SubmitDiarizeAudioJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcriptionServiceClient) GetDiarizeAudioJob(ctx context.Context, in *GetDiarizeAudioJobRequest, opts ...grpc.CallOption) (*GetDiarizeAudioJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiarizeAudioJobResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_GetDiarizeAudioJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscriptionServiceServer is the server API for TranscriptionService service.
// All implementations must embed UnimplementedTranscriptionServiceServer
// for forward compatibility.
type TranscriptionServiceServer interface {
	Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error)
	SubmitTranscribeJob(context.Context, *TranscribeRequest) (*SubmitTranscribeJobResponse, error)
	GetTranscribeJob(context.Context, *GetTranscribeJobRequest) (*GetTranscribeJobResponse, error)
	DiarizeAudio(context.Context, *DiarizeAudioRequest) (*DiarizeAudioResponse, error)
	SubmitDiarizeAudioJob(context.Context, *DiarizeAudioRequest) (*SubmitDiarizeAudioJobResponse, error)
	GetDiarizeAudioJob(context.Context, *GetDiarizeAudioJobRequest) (*GetDiarizeAudioJobResponse, error)
	mustEmbedUnimplementedTranscriptionServiceServer()
}

// UnimplementedTranscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscriptionServiceServer struct{}

func (UnimplementedTranscriptionServiceServer) Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedTranscriptionServiceServer) SubmitTranscribeJob(context.Context, *TranscribeRequest) (*SubmitTranscribeJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTranscribeJob not implemented")
}
func (UnimplementedTranscriptionServiceServer) GetTranscribeJob(context.Context, *GetTranscribeJobRequest) (*GetTranscribeJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranscribeJob not implemented")
}
func (UnimplementedTranscriptionServiceServer) DiarizeAudio(context.Context, *DiarizeAudioRequest) (*DiarizeAudioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiarizeAudio not implemented")
}
func (UnimplementedTranscriptionServiceServer) SubmitDiarizeAudioJob(context.Context, *DiarizeAudioRequest) (*SubmitDiarizeAudioJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitDiarizeAudioJob not implemented")
}
func (UnimplementedTranscriptionServiceServer) GetDiarizeAudioJob(context.Context, *GetDiarizeAudioJobRequest) (*GetDiarizeAudioJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiarizeAudioJob not implemented")
}
func (UnimplementedTranscriptionServiceServer) mustEmbedUnimplementedTranscriptionServiceServer() {}
func (UnimplementedTranscriptionServiceServer) testEmbeddedByValue()                              {}

// UnsafeTranscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscriptionServiceServer will
// result in compilation errors.
type UnsafeTranscriptionServiceServer interface {
	mustEmbedUnimplementedTranscriptionServiceServer()
}

func RegisterTranscriptionServiceServer(s grpc.ServiceRegistrar, srv TranscriptionServiceServer) {
	// If the following call pancis, it indicates UnimplementedTranscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranscriptionService_ServiceDesc, srv)
}

func _TranscriptionService_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).Transcribe(ctx, req.(*TranscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscriptionService_SubmitTranscribeJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).SubmitTranscribeJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_SubmitTranscribeJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).SubmitTranscribeJob(ctx, req.(*TranscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscriptionService_GetTranscribeJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranscribeJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).GetTranscribeJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_GetTranscribeJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).GetTranscribeJob(ctx, req.(*GetTranscribeJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscriptionService_DiarizeAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiarizeAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).DiarizeAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_DiarizeAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).DiarizeAudio(ctx, req.(*DiarizeAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscriptionService_SubmitDiarizeAudioJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiarizeAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).SubmitDiarizeAudioJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_SubmitDiarizeAudioJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).SubmitDiarizeAudioJob(ctx, req.(*DiarizeAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscriptionService_GetDiarizeAudioJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiarizeAudioJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).GetDiarizeAudioJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_GetDiarizeAudioJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).GetDiarizeAudioJob(ctx, req.(*GetDiarizeAudioJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranscriptionService_ServiceDesc is the grpc.ServiceDesc for TranscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dictator.speech.v1.TranscriptionService",
	HandlerType: (*TranscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transcribe",
			Handler:    _TranscriptionService_Transcribe_Handler,
		},
		{
			MethodName: "SubmitTranscribeJob",
			Handler:    _TranscriptionService_SubmitTranscribeJob_Handler,
		},
		{
			MethodName: "GetTranscribeJob",
			Handler:    _TranscriptionService_GetTranscribeJob_Handler,
		},
		{
			MethodName: "DiarizeAudio",
			Handler:    _TranscriptionService_DiarizeAudio_Handler,
		},
		{
			MethodName: "SubmitDiarizeAudioJob",
			Handler:    _TranscriptionService_SubmitDiarizeAudioJob_Handler,
		},
		{
			MethodName: "GetDiarizeAudioJob",
			Handler:    _TranscriptionService_GetDiarizeAudioJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dictator/speech/v1/transcription.proto",
}
