// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: dictator/speech/v1/voice.proto

package dictatorspeechv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceService_ExtractReferenceSample_FullMethodName          = "/dictator.speech.v1.VoiceService/ExtractReferenceSample"
	VoiceService_SubmitExtractReferenceSampleJob_FullMethodName = "/dictator.speech.v1.VoiceService/SubmitExtractReferenceSampleJob"
	VoiceService_GetExtractReferenceSampleJob_FullMethodName    = "/dictator.speech.v1.VoiceService/GetExtractReferenceSampleJob"
	VoiceService_SynthesizeSpeech_FullMethodName                = "/dictator.speech.v1.VoiceService/SynthesizeSpeech"
	VoiceService_SubmitSynthesizeSpeechJob_FullMethodName       = "/dictator.speech.v1.VoiceService/SubmitSynthesizeSpeechJob"
	VoiceService_GetSynthesizeSpeechJob_FullMethodName          = "/dictator.speech.v1.VoiceService/GetSynthesizeSpeechJob"
)

// VoiceServiceClient is the client API for VoiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceServiceClient interface {
	ExtractReferenceSample(ctx context.Context, in *ExtractReferenceSampleRequest, opts ...grpc.CallOption) (*ExtractReferenceSampleResponse, error)
	SubmitExtractReferenceSampleJob(ctx context.Context, in *ExtractReferenceSampleRequest, opts ...grpc.CallOption) (*SubmitExtractReferenceSampleJobResponse, error)
	GetExtractReferenceSampleJob(ctx context.Context, in *GetExtractReferenceSampleJobRequest, opts ...grpc.CallOption) (*GetExtractReferenceSampleJobResponse, error)
	SynthesizeSpeech(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (*SynthesizeSpeechResponse, error)
	SubmitSynthesizeSpeechJob(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (*SubmitSynthesizeSpeechJobResponse, error)
	GetSynthesizeSpeechJob(ctx context.Context, in *GetSynthesizeSpeechJobRequest, opts ...grpc.CallOption) (*GetSynthesizeSpeechJobResponse, error)
}

type voiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceServiceClient(cc grpc.ClientConnInterface) VoiceServiceClient {
	return &voiceServiceClient{cc}
}

func (c *voiceServiceClient) ExtractReferenceSample(ctx context.Context, in *ExtractReferenceSampleRequest, opts ...grpc.CallOption) (*ExtractReferenceSampleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractReferenceSampleResponse)
	err := c.cc.Invoke(ctx, VoiceService_ExtractReferenceSample_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) SubmitExtractReferenceSampleJob(ctx context.Context, in *ExtractReferenceSampleRequest, opts ...grpc.CallOption) (*SubmitExtractReferenceSampleJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitExtractReferenceSampleJobResponse)
	err := c.cc.Invoke(ctx, VoiceService_SubmitExtractReferenceSampleJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetExtractReferenceSampleJob(ctx context.Context, in *GetExtractReferenceSampleJobRequest, opts ...grpc.CallOption) (*GetExtractReferenceSampleJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExtractReferenceSampleJobResponse)
	err := c.cc.Invoke(ctx, VoiceService_GetExtractReferenceSampleJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) SynthesizeSpeech(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (*SynthesizeSpeechResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesizeSpeechResponse)
	err := c.cc.Invoke(ctx, VoiceService_SynthesizeSpeech_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) SubmitSynthesizeSpeechJob(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (*SubmitSynthesizeSpeechJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSynthesizeSpeechJobResponse)
	err := c.cc.Invoke(ctx, VoiceService_SubmitSynthesizeSpeechJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceServiceClient) GetSynthesizeSpeechJob(ctx context.Context, in *GetSynthesizeSpeechJobRequest, opts ...grpc.CallOption) (*GetSynthesizeSpeechJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSynthesizeSpeechJobResponse)
	err := c.cc.Invoke(ctx, VoiceService_GetSynthesizeSpeechJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceServiceServer is the server API for VoiceService service.
// All implementations must embed UnimplementedVoiceServiceServer
// for forward compatibility.
type VoiceServiceServer interface {
	ExtractReferenceSample(context.Context, *ExtractReferenceSampleRequest) (*ExtractReferenceSampleResponse, error)
	SubmitExtractReferenceSampleJob(context.Context, *ExtractReferenceSampleRequest) (*SubmitExtractReferenceSampleJobResponse, error)
	GetExtractReferenceSampleJob(context.Context, *GetExtractReferenceSampleJobRequest) (*GetExtractReferenceSampleJobResponse, error)
	SynthesizeSpeech(context.Context, *SynthesizeSpeechRequest) (*SynthesizeSpeechResponse, error)
	SubmitSynthesizeSpeechJob(context.Context, *SynthesizeSpeechRequest) (*SubmitSynthesizeSpeechJobResponse, error)
	GetSynthesizeSpeechJob(context.Context, *GetSynthesizeSpeechJobRequest) (*GetSynthesizeSpeechJobResponse, error)
	mustEmbedUnimplementedVoiceServiceServer()
}

// UnimplementedVoiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceServiceServer struct{}

func (UnimplementedVoiceServiceServer) ExtractReferenceSample(context.Context, *ExtractReferenceSampleRequest) (*ExtractReferenceSampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractReferenceSample not implemented")
}
func (UnimplementedVoiceServiceServer) SubmitExtractReferenceSampleJob(context.Context, *ExtractReferenceSampleRequest) (*SubmitExtractReferenceSampleJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitExtractReferenceSampleJob not implemented")
}
func (UnimplementedVoiceServiceServer) GetExtractReferenceSampleJob(context.Context, *GetExtractReferenceSampleJobRequest) (*GetExtractReferenceSampleJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtractReferenceSampleJob not implemented")
}
func (UnimplementedVoiceServiceServer) SynthesizeSpeech(context.Context, *SynthesizeSpeechRequest) (*SynthesizeSpeechResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SynthesizeSpeech not implemented")
}
func (UnimplementedVoiceServiceServer) SubmitSynthesizeSpeechJob(context.Context, *SynthesizeSpeechRequest) (*SubmitSynthesizeSpeechJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSynthesizeSpeechJob not implemented")
}
func (UnimplementedVoiceServiceServer) GetSynthesizeSpeechJob(context.Context, *GetSynthesizeSpeechJobRequest) (*GetSynthesizeSpeechJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSynthesizeSpeechJob not implemented")
}
func (UnimplementedVoiceServiceServer) mustEmbedUnimplementedVoiceServiceServer() {}
func (UnimplementedVoiceServiceServer) testEmbeddedByValue()                      {}

// UnsafeVoiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceServiceServer will
// result in compilation errors.
type UnsafeVoiceServiceServer interface {
	mustEmbedUnimplementedVoiceServiceServer()
}

func RegisterVoiceServiceServer(s grpc.ServiceRegistrar, srv VoiceServiceServer) {
	// If the following call pancis, it indicates UnimplementedVoiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceService_ServiceDesc, srv)
}

func _VoiceService_ExtractReferenceSample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractReferenceSampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).ExtractReferenceSample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_ExtractReferenceSample_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).ExtractReferenceSample(ctx, req.(*ExtractReferenceSampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_SubmitExtractReferenceSampleJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractReferenceSampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).SubmitExtractReferenceSampleJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_SubmitExtractReferenceSampleJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).SubmitExtractReferenceSampleJob(ctx, req.(*ExtractReferenceSampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetExtractReferenceSampleJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtractReferenceSampleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetExtractReferenceSampleJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetExtractReferenceSampleJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetExtractReferenceSampleJob(ctx, req.(*GetExtractReferenceSampleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_SynthesizeSpeech_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizeSpeechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).SynthesizeSpeech(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_SynthesizeSpeech_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).SynthesizeSpeech(ctx, req.(*SynthesizeSpeechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_SubmitSynthesizeSpeechJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizeSpeechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).SubmitSynthesizeSpeechJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_SubmitSynthesizeSpeechJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).SubmitSynthesizeSpeechJob(ctx, req.(*SynthesizeSpeechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceService_GetSynthesizeSpeechJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSynthesizeSpeechJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServiceServer).GetSynthesizeSpeechJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceService_GetSynthesizeSpeechJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServiceServer).GetSynthesizeSpeechJob(ctx, req.(*GetSynthesizeSpeechJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoiceService_ServiceDesc is the grpc.ServiceDesc for VoiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dictator.speech.v1.VoiceService",
	HandlerType: (*VoiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractReferenceSample",
			Handler:    _VoiceService_ExtractReferenceSample_Handler,
		},
		{
			MethodName: "SubmitExtractReferenceSampleJob",
			Handler:    _VoiceService_SubmitExtractReferenceSampleJob_Handler,
		},
		{
			MethodName: "GetExtractReferenceSampleJob",
			Handler:    _VoiceService_GetExtractReferenceSampleJob_Handler,
		},
		{
			MethodName: "SynthesizeSpeech",
			Handler:    _VoiceService_SynthesizeSpeech_Handler,
		},
		{
			MethodName: "SubmitSynthesizeSpeechJob",
			Handler:    _VoiceService_SubmitSynthesizeSpeechJob_Handler,
		},
		{
			MethodName: "GetSynthesizeSpeechJob",
			Handler:    _VoiceService_GetSynthesizeSpeechJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dictator/speech/v1/voice.proto",
}
