// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: dictator/speech/v1/voice.proto

package dictatorspeechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SynthesisEngine int32

const (
	SynthesisEngine_SYNTHESIS_ENGINE_UNSPECIFIED SynthesisEngine = 0
	SynthesisEngine_SYNTHESIS_ENGINE_QWEN3       SynthesisEngine = 1
	SynthesisEngine_SYNTHESIS_ENGINE_SILERO_RU   SynthesisEngine = 2
)

// Enum value maps for SynthesisEngine.
var (
	SynthesisEngine_name = map[int32]string{
		0: "SYNTHESIS_ENGINE_UNSPECIFIED",
		1: "SYNTHESIS_ENGINE_QWEN3",
		2: "SYNTHESIS_ENGINE_SILERO_RU",
	}
	SynthesisEngine_value = map[string]int32{
		"SYNTHESIS_ENGINE_UNSPECIFIED": 0,
		"SYNTHESIS_ENGINE_QWEN3":       1,
		"SYNTHESIS_ENGINE_SILERO_RU":   2,
	}
)

func (x SynthesisEngine) Enum() *SynthesisEngine {
	p := new(SynthesisEngine)
	*p = x
	return p
}

func (x SynthesisEngine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SynthesisEngine) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_voice_proto_enumTypes[0].Descriptor()
}

func (SynthesisEngine) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_voice_proto_enumTypes[0]
}

func (x SynthesisEngine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SynthesisEngine.Descriptor instead.
func (SynthesisEngine) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{0}
}

type SynthesisJobState int32

const (
	SynthesisJobState_SYNTHESIS_JOB_STATE_UNSPECIFIED SynthesisJobState = 0
	SynthesisJobState_SYNTHESIS_JOB_STATE_QUEUED      SynthesisJobState = 1
	SynthesisJobState_SYNTHESIS_JOB_STATE_RUNNING     SynthesisJobState = 2
	SynthesisJobState_SYNTHESIS_JOB_STATE_SUCCEEDED   SynthesisJobState = 3
	SynthesisJobState_SYNTHESIS_JOB_STATE_FAILED      SynthesisJobState = 4
	SynthesisJobState_SYNTHESIS_JOB_STATE_CANCELED    SynthesisJobState = 5
)

// Enum value maps for SynthesisJobState.
var (
	SynthesisJobState_name = map[int32]string{
		0: "SYNTHESIS_JOB_STATE_UNSPECIFIED",
		1: "SYNTHESIS_JOB_STATE_QUEUED",
		2: "SYNTHESIS_JOB_STATE_RUNNING",
		3: "SYNTHESIS_JOB_STATE_SUCCEEDED",
		4: "SYNTHESIS_JOB_STATE_FAILED",
		5: "SYNTHESIS_JOB_STATE_CANCELED",
	}
	SynthesisJobState_value = map[string]int32{
		"SYNTHESIS_JOB_STATE_UNSPECIFIED": 0,
		"SYNTHESIS_JOB_STATE_QUEUED":      1,
		"SYNTHESIS_JOB_STATE_RUNNING":     2,
		"SYNTHESIS_JOB_STATE_SUCCEEDED":   3,
		"SYNTHESIS_JOB_STATE_FAILED":      4,
		"SYNTHESIS_JOB_STATE_CANCELED":    5,
	}
)

func (x SynthesisJobState) Enum() *SynthesisJobState {
	p := new(SynthesisJobState)
	*p = x
	return p
}

func (x SynthesisJobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SynthesisJobState) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_voice_proto_enumTypes[1].Descriptor()
}

func (SynthesisJobState) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_voice_proto_enumTypes[1]
}

func (x SynthesisJobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SynthesisJobState.Descriptor instead.
func (SynthesisJobState) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{1}
}

type ExtractReferenceSampleJobState int32

const (
	ExtractReferenceSampleJobState_EXTRACT_REFERENCE_SAMPLE_JOB_STATE_UNSPECIFIED ExtractReferenceSampleJobState = 0
	ExtractReferenceSampleJobState_EXTRACT_REFERENCE_SAMPLE_JOB_STATE_QUEUED      ExtractReferenceSampleJobState = 1
	ExtractReferenceSampleJobState_EXTRACT_REFERENCE_SAMPLE_JOB_STATE_RUNNING     ExtractReferenceSampleJobState = 2
	ExtractReferenceSampleJobState_EXTRACT_REFERENCE_SAMPLE_JOB_STATE_SUCCEEDED   ExtractReferenceSampleJobState = 3
	ExtractReferenceSampleJobState_EXTRACT_REFERENCE_SAMPLE_JOB_STATE_FAILED      ExtractReferenceSampleJobState = 4
	ExtractReferenceSampleJobState_EXTRACT_REFERENCE_SAMPLE_JOB_STATE_CANCELED    ExtractReferenceSampleJobState = 5
)

// Enum value maps for ExtractReferenceSampleJobState.
var (
	ExtractReferenceSampleJobState_name = map[int32]string{
		0: "EXTRACT_REFERENCE_SAMPLE_JOB_STATE_UNSPECIFIED",
		1: "EXTRACT_REFERENCE_SAMPLE_JOB_STATE_QUEUED",
		2: "EXTRACT_REFERENCE_SAMPLE_JOB_STATE_RUNNING",
		3: "EXTRACT_REFERENCE_SAMPLE_JOB_STATE_SUCCEEDED",
		4: "EXTRACT_REFERENCE_SAMPLE_JOB_STATE_FAILED",
		5: "EXTRACT_REFERENCE_SAMPLE_JOB_STATE_CANCELED",
	}
	ExtractReferenceSampleJobState_value = map[string]int32{
		"EXTRACT_REFERENCE_SAMPLE_JOB_STATE_UNSPECIFIED": 0,
		"EXTRACT_REFERENCE_SAMPLE_JOB_STATE_QUEUED":      1,
		"EXTRACT_REFERENCE_SAMPLE_JOB_STATE_RUNNING":     2,
		"EXTRACT_REFERENCE_SAMPLE_JOB_STATE_SUCCEEDED":   3,
		"EXTRACT_REFERENCE_SAMPLE_JOB_STATE_FAILED":      4,
		"EXTRACT_REFERENCE_SAMPLE_JOB_STATE_CANCELED":    5,
	}
)

func (x ExtractReferenceSampleJobState) Enum() *ExtractReferenceSampleJobState {
	p := new(ExtractReferenceSampleJobState)
	*p = x
	return p
}

func (x ExtractReferenceSampleJobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtractReferenceSampleJobState) Descriptor() protoreflect.EnumDescriptor {
	return file_dictator_speech_v1_voice_proto_enumTypes[2].Descriptor()
}

func (ExtractReferenceSampleJobState) Type() protoreflect.EnumType {
	return &file_dictator_speech_v1_voice_proto_enumTypes[2]
}

func (x ExtractReferenceSampleJobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtractReferenceSampleJobState.Descriptor instead.
func (ExtractReferenceSampleJobState) EnumDescriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{2}
}

type ExtractReferenceSampleRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceArtifactId string                 `protobuf:"bytes,1,opt,name=source_artifact_id,json=sourceArtifactId,proto3" json:"source_artifact_id,omitempty"`
	ModelSize        string                 `protobuf:"bytes,2,opt,name=model_size,json=modelSize,proto3" json:"model_size,omitempty"`
	LanguageCode     string                 `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	DurationSeconds  float64                `protobuf:"fixed64,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	MaxSpeechRate    float64                `protobuf:"fixed64,5,opt,name=max_speech_rate,json=maxSpeechRate,proto3" json:"max_speech_rate,omitempty"`
	MinCentroidHz    float64                `protobuf:"fixed64,6,opt,name=min_centroid_hz,json=minCentroidHz,proto3" json:"min_centroid_hz,omitempty"`
	MaxCentroidHz    float64                `protobuf:"fixed64,7,opt,name=max_centroid_hz,json=maxCentroidHz,proto3" json:"max_centroid_hz,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtractReferenceSampleRequest) Reset() {
	*x = ExtractReferenceSampleRequest{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractReferenceSampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractReferenceSampleRequest) ProtoMessage() {}

func (x *ExtractReferenceSampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractReferenceSampleRequest.ProtoReflect.Descriptor instead.
func (*ExtractReferenceSampleRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractReferenceSampleRequest) GetSourceArtifactId() string {
	if x != nil {
		return x.SourceArtifactId
	}
	return ""
}

func (x *ExtractReferenceSampleRequest) GetModelSize() string {
	if x != nil {
		return x.ModelSize
	}
	return ""
}

func (x *ExtractReferenceSampleRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *ExtractReferenceSampleRequest) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ExtractReferenceSampleRequest) GetMaxSpeechRate() float64 {
	if x != nil {
		return x.MaxSpeechRate
	}
	return 0
}

func (x *ExtractReferenceSampleRequest) GetMinCentroidHz() float64 {
	if x != nil {
		return x.MinCentroidHz
	}
	return 0
}

func (x *ExtractReferenceSampleRequest) GetMaxCentroidHz() float64 {
	if x != nil {
		return x.MaxCentroidHz
	}
	return 0
}

type ExtractReferenceSampleResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SampleArtifact           *ArtifactRef           `protobuf:"bytes,1,opt,name=sample_artifact,json=sampleArtifact,proto3" json:"sample_artifact,omitempty"`
	TrimStartSeconds         float64                `protobuf:"fixed64,2,opt,name=trim_start_seconds,json=trimStartSeconds,proto3" json:"trim_start_seconds,omitempty"`
	TrimEndSeconds           float64                `protobuf:"fixed64,3,opt,name=trim_end_seconds,json=trimEndSeconds,proto3" json:"trim_end_seconds,omitempty"`
	WindowStartSeconds       float64                `protobuf:"fixed64,4,opt,name=window_start_seconds,json=windowStartSeconds,proto3" json:"window_start_seconds,omitempty"`
	WindowEndSeconds         float64                `protobuf:"fixed64,5,opt,name=window_end_seconds,json=windowEndSeconds,proto3" json:"window_end_seconds,omitempty"`
	DominantSpeakerWordCount int32                  `protobuf:"varint,6,opt,name=dominant_speaker_word_count,json=dominantSpeakerWordCount,proto3" json:"dominant_speaker_word_count,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExtractReferenceSampleResponse) Reset() {
	*x = ExtractReferenceSampleResponse{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractReferenceSampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractReferenceSampleResponse) ProtoMessage() {}

func (x *ExtractReferenceSampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractReferenceSampleResponse.ProtoReflect.Descriptor instead.
func (*ExtractReferenceSampleResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractReferenceSampleResponse) GetSampleArtifact() *ArtifactRef {
	if x != nil {
		return x.SampleArtifact
	}
	return nil
}

func (x *ExtractReferenceSampleResponse) GetTrimStartSeconds() float64 {
	if x != nil {
		return x.TrimStartSeconds
	}
	return 0
}

func (x *ExtractReferenceSampleResponse) GetTrimEndSeconds() float64 {
	if x != nil {
		return x.TrimEndSeconds
	}
	return 0
}

func (x *ExtractReferenceSampleResponse) GetWindowStartSeconds() float64 {
	if x != nil {
		return x.WindowStartSeconds
	}
	return 0
}

func (x *ExtractReferenceSampleResponse) GetWindowEndSeconds() float64 {
	if x != nil {
		return x.WindowEndSeconds
	}
	return 0
}

func (x *ExtractReferenceSampleResponse) GetDominantSpeakerWordCount() int32 {
	if x != nil {
		return x.DominantSpeakerWordCount
	}
	return 0
}

type SubmitExtractReferenceSampleJobResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	JobId         string                         `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         ExtractReferenceSampleJobState `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.ExtractReferenceSampleJobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitExtractReferenceSampleJobResponse) Reset() {
	*x = SubmitExtractReferenceSampleJobResponse{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitExtractReferenceSampleJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitExtractReferenceSampleJobResponse) ProtoMessage() {}

func (x *SubmitExtractReferenceSampleJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitExtractReferenceSampleJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitExtractReferenceSampleJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitExtractReferenceSampleJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitExtractReferenceSampleJobResponse) GetState() ExtractReferenceSampleJobState {
	if x != nil {
		return x.State
	}
	return ExtractReferenceSampleJobState_EXTRACT_REFERENCE_SAMPLE_JOB_STATE_UNSPECIFIED
}

type GetExtractReferenceSampleJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtractReferenceSampleJobRequest) Reset() {
	*x = GetExtractReferenceSampleJobRequest{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtractReferenceSampleJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtractReferenceSampleJobRequest) ProtoMessage() {}

func (x *GetExtractReferenceSampleJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtractReferenceSampleJobRequest.ProtoReflect.Descriptor instead.
func (*GetExtractReferenceSampleJobRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{3}
}

func (x *GetExtractReferenceSampleJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetExtractReferenceSampleJobResponse struct {
	state                    protoimpl.MessageState         `protogen:"open.v1"`
	JobId                    string                         `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State                    ExtractReferenceSampleJobState `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.ExtractReferenceSampleJobState" json:"state,omitempty"`
	ErrorCode                string                         `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage             string                         `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SampleArtifact           *ArtifactRef                   `protobuf:"bytes,5,opt,name=sample_artifact,json=sampleArtifact,proto3" json:"sample_artifact,omitempty"`
	TrimStartSeconds         float64                        `protobuf:"fixed64,6,opt,name=trim_start_seconds,json=trimStartSeconds,proto3" json:"trim_start_seconds,omitempty"`
	TrimEndSeconds           float64                        `protobuf:"fixed64,7,opt,name=trim_end_seconds,json=trimEndSeconds,proto3" json:"trim_end_seconds,omitempty"`
	WindowStartSeconds       float64                        `protobuf:"fixed64,8,opt,name=window_start_seconds,json=windowStartSeconds,proto3" json:"window_start_seconds,omitempty"`
	WindowEndSeconds         float64                        `protobuf:"fixed64,9,opt,name=window_end_seconds,json=windowEndSeconds,proto3" json:"window_end_seconds,omitempty"`
	DominantSpeakerWordCount int32                          `protobuf:"varint,10,opt,name=dominant_speaker_word_count,json=dominantSpeakerWordCount,proto3" json:"dominant_speaker_word_count,omitempty"`
	CreatedAtUnixSeconds     float64                        `protobuf:"fixed64,11,opt,name=created_at_unix_seconds,json=createdAtUnixSeconds,proto3" json:"created_at_unix_seconds,omitempty"`
	StartedAtUnixSeconds     float64                        `protobuf:"fixed64,12,opt,name=started_at_unix_seconds,json=startedAtUnixSeconds,proto3" json:"started_at_unix_seconds,omitempty"`
	FinishedAtUnixSeconds    float64                        `protobuf:"fixed64,13,opt,name=finished_at_unix_seconds,json=finishedAtUnixSeconds,proto3" json:"finished_at_unix_seconds,omitempty"`
	SourceArtifactId         string                         `protobuf:"bytes,14,opt,name=source_artifact_id,json=sourceArtifactId,proto3" json:"source_artifact_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetExtractReferenceSampleJobResponse) Reset() {
	*x = GetExtractReferenceSampleJobResponse{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtractReferenceSampleJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtractReferenceSampleJobResponse) ProtoMessage() {}

func (x *GetExtractReferenceSampleJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtractReferenceSampleJobResponse.ProtoReflect.Descriptor instead.
func (*GetExtractReferenceSampleJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{4}
}

func (x *GetExtractReferenceSampleJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetExtractReferenceSampleJobResponse) GetState() ExtractReferenceSampleJobState {
	if x != nil {
		return x.State
	}
	return ExtractReferenceSampleJobState_EXTRACT_REFERENCE_SAMPLE_JOB_STATE_UNSPECIFIED
}

func (x *GetExtractReferenceSampleJobResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetExtractReferenceSampleJobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetExtractReferenceSampleJobResponse) GetSampleArtifact() *ArtifactRef {
	if x != nil {
		return x.SampleArtifact
	}
	return nil
}

func (x *GetExtractReferenceSampleJobResponse) GetTrimStartSeconds() float64 {
	if x != nil {
		return x.TrimStartSeconds
	}
	return 0
}

func (x *GetExtractReferenceSampleJobResponse) GetTrimEndSeconds() float64 {
	if x != nil {
		return x.TrimEndSeconds
	}
	return 0
}

func (x *GetExtractReferenceSampleJobResponse) GetWindowStartSeconds() float64 {
	if x != nil {
		return x.WindowStartSeconds
	}
	return 0
}

func (x *GetExtractReferenceSampleJobResponse) GetWindowEndSeconds() float64 {
	if x != nil {
		return x.WindowEndSeconds
	}
	return 0
}

func (x *GetExtractReferenceSampleJobResponse) GetDominantSpeakerWordCount() int32 {
	if x != nil {
		return x.DominantSpeakerWordCount
	}
	return 0
}

func (x *GetExtractReferenceSampleJobResponse) GetCreatedAtUnixSeconds() float64 {
	if x != nil {
		return x.CreatedAtUnixSeconds
	}
	return 0
}

func (x *GetExtractReferenceSampleJobResponse) GetStartedAtUnixSeconds() float64 {
	if x != nil {
		return x.StartedAtUnixSeconds
	}
	return 0
}

func (x *GetExtractReferenceSampleJobResponse) GetFinishedAtUnixSeconds() float64 {
	if x != nil {
		return x.FinishedAtUnixSeconds
	}
	return 0
}

func (x *GetExtractReferenceSampleJobResponse) GetSourceArtifactId() string {
	if x != nil {
		return x.SourceArtifactId
	}
	return ""
}

type CancelExtractReferenceSampleJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExtractReferenceSampleJobRequest) Reset() {
	*x = CancelExtractReferenceSampleJobRequest{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExtractReferenceSampleJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExtractReferenceSampleJobRequest) ProtoMessage() {}

func (x *CancelExtractReferenceSampleJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExtractReferenceSampleJobRequest.ProtoReflect.Descriptor instead.
func (*CancelExtractReferenceSampleJobRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{5}
}

func (x *CancelExtractReferenceSampleJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelExtractReferenceSampleJobResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	JobId         string                         `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         ExtractReferenceSampleJobState `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.ExtractReferenceSampleJobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExtractReferenceSampleJobResponse) Reset() {
	*x = CancelExtractReferenceSampleJobResponse{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExtractReferenceSampleJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExtractReferenceSampleJobResponse) ProtoMessage() {}

func (x *CancelExtractReferenceSampleJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExtractReferenceSampleJobResponse.ProtoReflect.Descriptor instead.
func (*CancelExtractReferenceSampleJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{6}
}

func (x *CancelExtractReferenceSampleJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelExtractReferenceSampleJobResponse) GetState() ExtractReferenceSampleJobState {
	if x != nil {
		return x.State
	}
	return ExtractReferenceSampleJobState_EXTRACT_REFERENCE_SAMPLE_JOB_STATE_UNSPECIFIED
}

type SynthesizeSpeechRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SpeakerArtifactId string                 `protobuf:"bytes,1,opt,name=speaker_artifact_id,json=speakerArtifactId,proto3" json:"speaker_artifact_id,omitempty"`
	// Types that are valid to be assigned to TextSource:
	//
	//	*SynthesizeSpeechRequest_Text
	//	*SynthesizeSpeechRequest_TextArtifactId
	TextSource            isSynthesizeSpeechRequest_TextSource `protobuf_oneof:"text_source"`
	LanguageCode          string                               `protobuf:"bytes,4,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	MaxDurationSeconds    float64                              `protobuf:"fixed64,5,opt,name=max_duration_seconds,json=maxDurationSeconds,proto3" json:"max_duration_seconds,omitempty"`
	IncludeTimeline       bool                                 `protobuf:"varint,6,opt,name=include_timeline,json=includeTimeline,proto3" json:"include_timeline,omitempty"`
	SynthesisEngine       SynthesisEngine                      `protobuf:"varint,7,opt,name=synthesis_engine,json=synthesisEngine,proto3,enum=dictator.speech.v1.SynthesisEngine" json:"synthesis_engine,omitempty"`
	SpeakerTranscriptText string                               `protobuf:"bytes,8,opt,name=speaker_transcript_text,json=speakerTranscriptText,proto3" json:"speaker_transcript_text,omitempty"`
	AudioFormat           *AudioFormat                         `protobuf:"bytes,9,opt,name=audio_format,json=audioFormat,proto3" json:"audio_format,omitempty"`
	PresetSpeaker         string                               `protobuf:"bytes,10,opt,name=preset_speaker,json=presetSpeaker,proto3" json:"preset_speaker,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SynthesizeSpeechRequest) Reset() {
	*x = SynthesizeSpeechRequest{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSpeechRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSpeechRequest) ProtoMessage() {}

func (x *SynthesizeSpeechRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSpeechRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeSpeechRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{7}
}

func (x *SynthesizeSpeechRequest) GetSpeakerArtifactId() string {
	if x != nil {
		return x.SpeakerArtifactId
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetTextSource() isSynthesizeSpeechRequest_TextSource {
	if x != nil {
		return x.TextSource
	}
	return nil
}

func (x *SynthesizeSpeechRequest) GetText() string {
	if x != nil {
		if x, ok := x.TextSource.(*SynthesizeSpeechRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetTextArtifactId() string {
	if x != nil {
		if x, ok := x.TextSource.(*SynthesizeSpeechRequest_TextArtifactId); ok {
			return x.TextArtifactId
		}
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetMaxDurationSeconds() float64 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

func (x *SynthesizeSpeechRequest) GetIncludeTimeline() bool {
	if x != nil {
		return x.IncludeTimeline
	}
	return false
}

func (x *SynthesizeSpeechRequest) GetSynthesisEngine() SynthesisEngine {
	if x != nil {
		return x.SynthesisEngine
	}
	return SynthesisEngine_SYNTHESIS_ENGINE_UNSPECIFIED
}

func (x *SynthesizeSpeechRequest) GetSpeakerTranscriptText() string {
	if x != nil {
		return x.SpeakerTranscriptText
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetAudioFormat() *AudioFormat {
	if x != nil {
		return x.AudioFormat
	}
	return nil
}

func (x *SynthesizeSpeechRequest) GetPresetSpeaker() string {
	if x != nil {
		return x.PresetSpeaker
	}
	return ""
}

type isSynthesizeSpeechRequest_TextSource interface {
	isSynthesizeSpeechRequest_TextSource()
}

type SynthesizeSpeechRequest_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type SynthesizeSpeechRequest_TextArtifactId struct {
	TextArtifactId string `protobuf:"bytes,3,opt,name=text_artifact_id,json=textArtifactId,proto3,oneof"`
}

func (*SynthesizeSpeechRequest_Text) isSynthesizeSpeechRequest_TextSource() {}

func (*SynthesizeSpeechRequest_TextArtifactId) isSynthesizeSpeechRequest_TextSource() {}

type SynthesizeSpeechResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AudioArtifact        *ArtifactRef           `protobuf:"bytes,1,opt,name=audio_artifact,json=audioArtifact,proto3" json:"audio_artifact,omitempty"`
	AudioDurationSeconds float64                `protobuf:"fixed64,2,opt,name=audio_duration_seconds,json=audioDurationSeconds,proto3" json:"audio_duration_seconds,omitempty"`
	Timeline             []*TimelineSegment     `protobuf:"bytes,3,rep,name=timeline,proto3" json:"timeline,omitempty"`
	TimelineArtifactId   string                 `protobuf:"bytes,4,opt,name=timeline_artifact_id,json=timelineArtifactId,proto3" json:"timeline_artifact_id,omitempty"`
	ChunkCount           int32                  `protobuf:"varint,5,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	ResolvedAudioFormat  *AudioFormat           `protobuf:"bytes,6,opt,name=resolved_audio_format,json=resolvedAudioFormat,proto3" json:"resolved_audio_format,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SynthesizeSpeechResponse) Reset() {
	*x = SynthesizeSpeechResponse{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSpeechResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSpeechResponse) ProtoMessage() {}

func (x *SynthesizeSpeechResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSpeechResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeSpeechResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{8}
}

func (x *SynthesizeSpeechResponse) GetAudioArtifact() *ArtifactRef {
	if x != nil {
		return x.AudioArtifact
	}
	return nil
}

func (x *SynthesizeSpeechResponse) GetAudioDurationSeconds() float64 {
	if x != nil {
		return x.AudioDurationSeconds
	}
	return 0
}

func (x *SynthesizeSpeechResponse) GetTimeline() []*TimelineSegment {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *SynthesizeSpeechResponse) GetTimelineArtifactId() string {
	if x != nil {
		return x.TimelineArtifactId
	}
	return ""
}

func (x *SynthesizeSpeechResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *SynthesizeSpeechResponse) GetResolvedAudioFormat() *AudioFormat {
	if x != nil {
		return x.ResolvedAudioFormat
	}
	return nil
}

type SubmitSynthesizeSpeechJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         SynthesisJobState      `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.SynthesisJobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSynthesizeSpeechJobResponse) Reset() {
	*x = SubmitSynthesizeSpeechJobResponse{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSynthesizeSpeechJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSynthesizeSpeechJobResponse) ProtoMessage() {}

func (x *SubmitSynthesizeSpeechJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSynthesizeSpeechJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitSynthesizeSpeechJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitSynthesizeSpeechJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitSynthesizeSpeechJobResponse) GetState() SynthesisJobState {
	if x != nil {
		return x.State
	}
	return SynthesisJobState_SYNTHESIS_JOB_STATE_UNSPECIFIED
}

type GetSynthesizeSpeechJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSynthesizeSpeechJobRequest) Reset() {
	*x = GetSynthesizeSpeechJobRequest{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSynthesizeSpeechJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSynthesizeSpeechJobRequest) ProtoMessage() {}

func (x *GetSynthesizeSpeechJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSynthesizeSpeechJobRequest.ProtoReflect.Descriptor instead.
func (*GetSynthesizeSpeechJobRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{10}
}

func (x *GetSynthesizeSpeechJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetSynthesizeSpeechJobResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	JobId                 string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State                 SynthesisJobState      `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.SynthesisJobState" json:"state,omitempty"`
	ErrorCode             string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AudioArtifact         *ArtifactRef           `protobuf:"bytes,5,opt,name=audio_artifact,json=audioArtifact,proto3" json:"audio_artifact,omitempty"`
	AudioDurationSeconds  float64                `protobuf:"fixed64,6,opt,name=audio_duration_seconds,json=audioDurationSeconds,proto3" json:"audio_duration_seconds,omitempty"`
	TimelineArtifactId    string                 `protobuf:"bytes,7,opt,name=timeline_artifact_id,json=timelineArtifactId,proto3" json:"timeline_artifact_id,omitempty"`
	ChunkCount            int32                  `protobuf:"varint,8,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	CreatedAtUnixSeconds  float64                `protobuf:"fixed64,9,opt,name=created_at_unix_seconds,json=createdAtUnixSeconds,proto3" json:"created_at_unix_seconds,omitempty"`
	StartedAtUnixSeconds  float64                `protobuf:"fixed64,10,opt,name=started_at_unix_seconds,json=startedAtUnixSeconds,proto3" json:"started_at_unix_seconds,omitempty"`
	FinishedAtUnixSeconds float64                `protobuf:"fixed64,11,opt,name=finished_at_unix_seconds,json=finishedAtUnixSeconds,proto3" json:"finished_at_unix_seconds,omitempty"`
	EstimatedTotalChunks  int32                  `protobuf:"varint,12,opt,name=estimated_total_chunks,json=estimatedTotalChunks,proto3" json:"estimated_total_chunks,omitempty"`
	CompletedChunks       int32                  `protobuf:"varint,13,opt,name=completed_chunks,json=completedChunks,proto3" json:"completed_chunks,omitempty"`
	ResolvedAudioFormat   *AudioFormat           `protobuf:"bytes,14,opt,name=resolved_audio_format,json=resolvedAudioFormat,proto3" json:"resolved_audio_format,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSynthesizeSpeechJobResponse) Reset() {
	*x = GetSynthesizeSpeechJobResponse{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSynthesizeSpeechJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSynthesizeSpeechJobResponse) ProtoMessage() {}

func (x *GetSynthesizeSpeechJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSynthesizeSpeechJobResponse.ProtoReflect.Descriptor instead.
func (*GetSynthesizeSpeechJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{11}
}

func (x *GetSynthesizeSpeechJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetSynthesizeSpeechJobResponse) GetState() SynthesisJobState {
	if x != nil {
		return x.State
	}
	return SynthesisJobState_SYNTHESIS_JOB_STATE_UNSPECIFIED
}

func (x *GetSynthesizeSpeechJobResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetSynthesizeSpeechJobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetSynthesizeSpeechJobResponse) GetAudioArtifact() *ArtifactRef {
	if x != nil {
		return x.AudioArtifact
	}
	return nil
}

func (x *GetSynthesizeSpeechJobResponse) GetAudioDurationSeconds() float64 {
	if x != nil {
		return x.AudioDurationSeconds
	}
	return 0
}

func (x *GetSynthesizeSpeechJobResponse) GetTimelineArtifactId() string {
	if x != nil {
		return x.TimelineArtifactId
	}
	return ""
}

func (x *GetSynthesizeSpeechJobResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *GetSynthesizeSpeechJobResponse) GetCreatedAtUnixSeconds() float64 {
	if x != nil {
		return x.CreatedAtUnixSeconds
	}
	return 0
}

func (x *GetSynthesizeSpeechJobResponse) GetStartedAtUnixSeconds() float64 {
	if x != nil {
		return x.StartedAtUnixSeconds
	}
	return 0
}

func (x *GetSynthesizeSpeechJobResponse) GetFinishedAtUnixSeconds() float64 {
	if x != nil {
		return x.FinishedAtUnixSeconds
	}
	return 0
}

func (x *GetSynthesizeSpeechJobResponse) GetEstimatedTotalChunks() int32 {
	if x != nil {
		return x.EstimatedTotalChunks
	}
	return 0
}

func (x *GetSynthesizeSpeechJobResponse) GetCompletedChunks() int32 {
	if x != nil {
		return x.CompletedChunks
	}
	return 0
}

func (x *GetSynthesizeSpeechJobResponse) GetResolvedAudioFormat() *AudioFormat {
	if x != nil {
		return x.ResolvedAudioFormat
	}
	return nil
}

type CancelSynthesizeSpeechJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSynthesizeSpeechJobRequest) Reset() {
	*x = CancelSynthesizeSpeechJobRequest{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSynthesizeSpeechJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSynthesizeSpeechJobRequest) ProtoMessage() {}

func (x *CancelSynthesizeSpeechJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSynthesizeSpeechJobRequest.ProtoReflect.Descriptor instead.
func (*CancelSynthesizeSpeechJobRequest) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{12}
}

func (x *CancelSynthesizeSpeechJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelSynthesizeSpeechJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         SynthesisJobState      `protobuf:"varint,2,opt,name=state,proto3,enum=dictator.speech.v1.SynthesisJobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSynthesizeSpeechJobResponse) Reset() {
	*x = CancelSynthesizeSpeechJobResponse{}
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSynthesizeSpeechJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSynthesizeSpeechJobResponse) ProtoMessage() {}

func (x *CancelSynthesizeSpeechJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictator_speech_v1_voice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSynthesizeSpeechJobResponse.ProtoReflect.Descriptor instead.
func (*CancelSynthesizeSpeechJobResponse) Descriptor() ([]byte, []int) {
	return file_dictator_speech_v1_voice_proto_rawDescGZIP(), []int{13}
}

func (x *CancelSynthesizeSpeechJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelSynthesizeSpeechJobResponse) GetState() SynthesisJobState {
	if x != nil {
		return x.State
	}
	return SynthesisJobState_SYNTHESIS_JOB_STATE_UNSPECIFIED
}

var File_dictator_speech_v1_voice_proto protoreflect.FileDescriptor

const file_dictator_speech_v1_voice_proto_rawDesc = "" +
	"\n" +
	"\x1edictator/speech/v1/voice.proto\x12\x12dictator.speech.v1\x1a\x1fdictator/speech/v1/common.proto\"\xb4\x02\n" +
	"\x1dExtractReferenceSampleRequest\x12,\n" +
	"\x12source_artifact_id\x18\x01 \x01(\tR\x10sourceArtifactId\x12\x1d\n" +
	"\n" +
	"model_size\x18\x02 \x01(\tR\tmodelSize\x12#\n" +
	"\rlanguage_code\x18\x03 \x01(\tR\flanguageCode\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x01R\x0fdurationSeconds\x12&\n" +
	"\x0fmax_speech_rate\x18\x05 \x01(\x01R\rmaxSpeechRate\x12&\n" +
	"\x0fmin_centroid_hz\x18\x06 \x01(\x01R\rminCentroidHz\x12&\n" +
	"\x0fmax_centroid_hz\x18\a \x01(\x01R\rmaxCentroidHz\"\xe1\x02\n" +
	"\x1eExtractReferenceSampleResponse\x12H\n" +
	"\x0fsample_artifact\x18\x01 \x01(\v2\x1f.dictator.speech.v1.ArtifactRefR\x0esampleArtifact\x12,\n" +
	"\x12trim_start_seconds\x18\x02 \x01(\x01R\x10trimStartSeconds\x12(\n" +
	"\x10trim_end_seconds\x18\x03 \x01(\x01R\x0etrimEndSeconds\x120\n" +
	"\x14window_start_seconds\x18\x04 \x01(\x01R\x12windowStartSeconds\x12,\n" +
	"\x12window_end_seconds\x18\x05 \x01(\x01R\x10windowEndSeconds\x12=\n" +
	"\x1bdominant_speaker_word_count\x18\x06 \x01(\x05R\x18dominantSpeakerWordCount\"\x8a\x01\n" +
	"'SubmitExtractReferenceSampleJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12H\n" +
	"\x05state\x18\x02 \x01(\x0e22.dictator.speech.v1.ExtractReferenceSampleJobStateR\x05state\"<\n" +
	"#GetExtractReferenceSampleJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xe1\x05\n" +
	"$GetExtractReferenceSampleJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12H\n" +
	"\x05state\x18\x02 \x01(\x0e22.dictator.speech.v1.ExtractReferenceSampleJobStateR\x05state\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12H\n" +
	"\x0fsample_artifact\x18\x05 \x01(\v2\x1f.dictator.speech.v1.ArtifactRefR\x0esampleArtifact\x12,\n" +
	"\x12trim_start_seconds\x18\x06 \x01(\x01R\x10trimStartSeconds\x12(\n" +
	"\x10trim_end_seconds\x18\a \x01(\x01R\x0etrimEndSeconds\x120\n" +
	"\x14window_start_seconds\x18\b \x01(\x01R\x12windowStartSeconds\x12,\n" +
	"\x12window_end_seconds\x18\t \x01(\x01R\x10windowEndSeconds\x12=\n" +
	"\x1bdominant_speaker_word_count\x18\n" +
	" \x01(\x05R\x18dominantSpeakerWordCount\x125\n" +
	"\x17created_at_unix_seconds\x18\v \x01(\x01R\x14createdAtUnixSeconds\x125\n" +
	"\x17started_at_unix_seconds\x18\f \x01(\x01R\x14startedAtUnixSeconds\x127\n" +
	"\x18finished_at_unix_seconds\x18\r \x01(\x01R\x15finishedAtUnixSeconds\x12,\n" +
	"\x12source_artifact_id\x18\x0e \x01(\tR\x10sourceArtifactId\"?\n" +
	"&CancelExtractReferenceSampleJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x8a\x01\n" +
	"'CancelExtractReferenceSampleJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12H\n" +
	"\x05state\x18\x02 \x01(\x0e22.dictator.speech.v1.ExtractReferenceSampleJobStateR\x05state\"\x8f\x04\n" +
	"\x17SynthesizeSpeechRequest\x12.\n" +
	"\x13speaker_artifact_id\x18\x01 \x01(\tR\x11speakerArtifactId\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12*\n" +
	"\x10text_artifact_id\x18\x03 \x01(\tH\x00R\x0etextArtifactId\x12#\n" +
	"\rlanguage_code\x18\x04 \x01(\tR\flanguageCode\x120\n" +
	"\x14max_duration_seconds\x18\x05 \x01(\x01R\x12maxDurationSeconds\x12)\n" +
	"\x10include_timeline\x18\x06 \x01(\bR\x0fincludeTimeline\x12N\n" +
	"\x10synthesis_engine\x18\a \x01(\x0e2#.dictator.speech.v1.SynthesisEngineR\x0fsynthesisEngine\x126\n" +
	"\x17speaker_transcript_text\x18\b \x01(\tR\x15speakerTranscriptText\x12B\n" +
	"\faudio_format\x18\t \x01(\v2\x1f.dictator.speech.v1.AudioFormatR\vaudioFormat\x12%\n" +
	"\x0epreset_speaker\x18\n" +
	" \x01(\tR\rpresetSpeakerB\r\n" +
	"\vtext_source\"\x81\x03\n" +
	"\x18SynthesizeSpeechResponse\x12F\n" +
	"\x0eaudio_artifact\x18\x01 \x01(\v2\x1f.dictator.speech.v1.ArtifactRefR\raudioArtifact\x124\n" +
	"\x16audio_duration_seconds\x18\x02 \x01(\x01R\x14audioDurationSeconds\x12?\n" +
	"\btimeline\x18\x03 \x03(\v2#.dictator.speech.v1.TimelineSegmentR\btimeline\x120\n" +
	"\x14timeline_artifact_id\x18\x04 \x01(\tR\x12timelineArtifactId\x12\x1f\n" +
	"\vchunk_count\x18\x05 \x01(\x05R\n" +
	"chunkCount\x12S\n" +
	"\x15resolved_audio_format\x18\x06 \x01(\v2\x1f.dictator.speech.v1.AudioFormatR\x13resolvedAudioFormat\"w\n" +
	"!SubmitSynthesizeSpeechJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12;\n" +
	"\x05state\x18\x02 \x01(\x0e2%.dictator.speech.v1.SynthesisJobStateR\x05state\"6\n" +
	"\x1dGetSynthesizeSpeechJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xe6\x05\n" +
	"\x1eGetSynthesizeSpeechJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12;\n" +
	"\x05state\x18\x02 \x01(\x0e2%.dictator.speech.v1.SynthesisJobStateR\x05state\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12F\n" +
	"\x0eaudio_artifact\x18\x05 \x01(\v2\x1f.dictator.speech.v1.ArtifactRefR\raudioArtifact\x124\n" +
	"\x16audio_duration_seconds\x18\x06 \x01(\x01R\x14audioDurationSeconds\x120\n" +
	"\x14timeline_artifact_id\x18\a \x01(\tR\x12timelineArtifactId\x12\x1f\n" +
	"\vchunk_count\x18\b \x01(\x05R\n" +
	"chunkCount\x125\n" +
	"\x17created_at_unix_seconds\x18\t \x01(\x01R\x14createdAtUnixSeconds\x125\n" +
	"\x17started_at_unix_seconds\x18\n" +
	" \x01(\x01R\x14startedAtUnixSeconds\x127\n" +
	"\x18finished_at_unix_seconds\x18\v \x01(\x01R\x15finishedAtUnixSeconds\x124\n" +
	"\x16estimated_total_chunks\x18\f \x01(\x05R\x14estimatedTotalChunks\x12)\n" +
	"\x10completed_chunks\x18\r \x01(\x05R\x0fcompletedChunks\x12S\n" +
	"\x15resolved_audio_format\x18\x0e \x01(\v2\x1f.dictator.speech.v1.AudioFormatR\x13resolvedAudioFormat\"9\n" +
	" CancelSynthesizeSpeechJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"w\n" +
	"!CancelSynthesizeSpeechJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12;\n" +
	"\x05state\x18\x02 \x01(\x0e2%.dictator.speech.v1.SynthesisJobStateR\x05state*o\n" +
	"\x0fSynthesisEngine\x12 \n" +
	"\x1cSYNTHESIS_ENGINE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SYNTHESIS_ENGINE_QWEN3\x10\x01\x12\x1e\n" +
	"\x1aSYNTHESIS_ENGINE_SILERO_RU\x10\x02*\xde\x01\n" +
	"\x11SynthesisJobState\x12#\n" +
	"\x1fSYNTHESIS_JOB_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSYNTHESIS_JOB_STATE_QUEUED\x10\x01\x12\x1f\n" +
	"\x1bSYNTHESIS_JOB_STATE_RUNNING\x10\x02\x12!\n" +
	"\x1dSYNTHESIS_JOB_STATE_SUCCEEDED\x10\x03\x12\x1e\n" +
	"\x1aSYNTHESIS_JOB_STATE_FAILED\x10\x04\x12 \n" +
	"\x1cSYNTHESIS_JOB_STATE_CANCELED\x10\x05*\xc5\x02\n" +
	"\x1eExtractReferenceSampleJobState\x122\n" +
	".EXTRACT_REFERENCE_SAMPLE_JOB_STATE_UNSPECIFIED\x10\x00\x12-\n" +
	")EXTRACT_REFERENCE_SAMPLE_JOB_STATE_QUEUED\x10\x01\x12.\n" +
	"*EXTRACT_REFERENCE_SAMPLE_JOB_STATE_RUNNING\x10\x02\x120\n" +
	",EXTRACT_REFERENCE_SAMPLE_JOB_STATE_SUCCEEDED\x10\x03\x12-\n" +
	")EXTRACT_REFERENCE_SAMPLE_JOB_STATE_FAILED\x10\x04\x12/\n" +
	"+EXTRACT_REFERENCE_SAMPLE_JOB_STATE_CANCELED\x10\x052\xd0\b\n" +
	"\fVoiceService\x12\x7f\n" +
	"\x16ExtractReferenceSample\x121.dictator.speech.v1.ExtractReferenceSampleRequest\x1a2.dictator.speech.v1.ExtractReferenceSampleResponse\x12\x91\x01\n" +
	"\x1fSubmitExtractReferenceSampleJob\x121.dictator.speech.v1.ExtractReferenceSampleRequest\x1a;.dictator.speech.v1.SubmitExtractReferenceSampleJobResponse\x12\x91\x01\n" +
	"\x1cGetExtractReferenceSampleJob\x127.dictator.speech.v1.GetExtractReferenceSampleJobRequest\x1a8.dictator.speech.v1.GetExtractReferenceSampleJobResponse\x12\x9a\x01\n" +
	"\x1fCancelExtractReferenceSampleJob\x12:.dictator.speech.v1.CancelExtractReferenceSampleJobRequest\x1a;.dictator.speech.v1.CancelExtractReferenceSampleJobResponse\x12m\n" +
	"\x10SynthesizeSpeech\x12+.dictator.speech.v1.SynthesizeSpeechRequest\x1a,.dictator.speech.v1.SynthesizeSpeechResponse\x12\x7f\n" +
	"\x19SubmitSynthesizeSpeechJob\x12+.dictator.speech.v1.SynthesizeSpeechRequest\x1a5.dictator.speech.v1.SubmitSynthesizeSpeechJobResponse\x12\x7f\n" +
	"\x16GetSynthesizeSpeechJob\x121.dictator.speech.v1.GetSynthesizeSpeechJobRequest\x1a2.dictator.speech.v1.GetSynthesizeSpeechJobResponse\x12\x88\x01\n" +
	"\x19CancelSynthesizeSpeechJob\x124.dictator.speech.v1.CancelSynthesizeSpeechJobRequest\x1a5.dictator.speech.v1.CancelSynthesizeSpeechJobResponseBGZEgithub.com/tyemirov/dictator/sdk/go/dictatorspeechv1;dictatorspeechv1b\x06proto3"

var (
	file_dictator_speech_v1_voice_proto_rawDescOnce sync.Once
	file_dictator_speech_v1_voice_proto_rawDescData []byte
)

func file_dictator_speech_v1_voice_proto_rawDescGZIP() []byte {
	file_dictator_speech_v1_voice_proto_rawDescOnce.Do(func() {
		file_dictator_speech_v1_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_voice_proto_rawDesc), len(file_dictator_speech_v1_voice_proto_rawDesc)))
	})
	return file_dictator_speech_v1_voice_proto_rawDescData
}

var file_dictator_speech_v1_voice_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dictator_speech_v1_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_dictator_speech_v1_voice_proto_goTypes = []any{
	(SynthesisEngine)(0),                            // 0: dictator.speech.v1.SynthesisEngine
	(SynthesisJobState)(0),                          // 1: dictator.speech.v1.SynthesisJobState
	(ExtractReferenceSampleJobState)(0),             // 2: dictator.speech.v1.ExtractReferenceSampleJobState
	(*ExtractReferenceSampleRequest)(nil),           // 3: dictator.speech.v1.ExtractReferenceSampleRequest
	(*ExtractReferenceSampleResponse)(nil),          // 4: dictator.speech.v1.ExtractReferenceSampleResponse
	(*SubmitExtractReferenceSampleJobResponse)(nil), // 5: dictator.speech.v1.SubmitExtractReferenceSampleJobResponse
	(*GetExtractReferenceSampleJobRequest)(nil),     // 6: dictator.speech.v1.GetExtractReferenceSampleJobRequest
	(*GetExtractReferenceSampleJobResponse)(nil),    // 7: dictator.speech.v1.GetExtractReferenceSampleJobResponse
	(*CancelExtractReferenceSampleJobRequest)(nil),  // 8: dictator.speech.v1.CancelExtractReferenceSampleJobRequest
	(*CancelExtractReferenceSampleJobResponse)(nil), // 9: dictator.speech.v1.CancelExtractReferenceSampleJobResponse
	(*SynthesizeSpeechRequest)(nil),                 // 10: dictator.speech.v1.SynthesizeSpeechRequest
	(*SynthesizeSpeechResponse)(nil),                // 11: dictator.speech.v1.SynthesizeSpeechResponse
	(*SubmitSynthesizeSpeechJobResponse)(nil),       // 12: dictator.speech.v1.SubmitSynthesizeSpeechJobResponse
	(*GetSynthesizeSpeechJobRequest)(nil),           // 13: dictator.speech.v1.GetSynthesizeSpeechJobRequest
	(*GetSynthesizeSpeechJobResponse)(nil),          // 14: dictator.speech.v1.GetSynthesizeSpeechJobResponse
	(*CancelSynthesizeSpeechJobRequest)(nil),        // 15: dictator.speech.v1.CancelSynthesizeSpeechJobRequest
	(*CancelSynthesizeSpeechJobResponse)(nil),       // 16: dictator.speech.v1.CancelSynthesizeSpeechJobResponse
	(*ArtifactRef)(nil),                             // 17: dictator.speech.v1.ArtifactRef
	(*AudioFormat)(nil),                             // 18: dictator.speech.v1.AudioFormat
	(*TimelineSegment)(nil),                         // 19: dictator.speech.v1.TimelineSegment
}
var file_dictator_speech_v1_voice_proto_depIdxs = []int32{
	17, // 0: dictator.speech.v1.ExtractReferenceSampleResponse.sample_artifact:type_name -> dictator.speech.v1.ArtifactRef
	2,  // 1: dictator.speech.v1.SubmitExtractReferenceSampleJobResponse.state:type_name -> dictator.speech.v1.ExtractReferenceSampleJobState
	2,  // 2: dictator.speech.v1.GetExtractReferenceSampleJobResponse.state:type_name -> dictator.speech.v1.ExtractReferenceSampleJobState
	17, // 3: dictator.speech.v1.GetExtractReferenceSampleJobResponse.sample_artifact:type_name -> dictator.speech.v1.ArtifactRef
	2,  // 4: dictator.speech.v1.CancelExtractReferenceSampleJobResponse.state:type_name -> dictator.speech.v1.ExtractReferenceSampleJobState
	0,  // 5: dictator.speech.v1.SynthesizeSpeechRequest.synthesis_engine:type_name -> dictator.speech.v1.SynthesisEngine
	18, // 6: dictator.speech.v1.SynthesizeSpeechRequest.audio_format:type_name -> dictator.speech.v1.AudioFormat
	17, // 7: dictator.speech.v1.SynthesizeSpeechResponse.audio_artifact:type_name -> dictator.speech.v1.ArtifactRef
	19, // 8: dictator.speech.v1.SynthesizeSpeechResponse.timeline:type_name -> dictator.speech.v1.TimelineSegment
	18, // 9: dictator.speech.v1.SynthesizeSpeechResponse.resolved_audio_format:type_name -> dictator.speech.v1.AudioFormat
	1,  // 10: dictator.speech.v1.SubmitSynthesizeSpeechJobResponse.state:type_name -> dictator.speech.v1.SynthesisJobState
	1,  // 11: dictator.speech.v1.GetSynthesizeSpeechJobResponse.state:type_name -> dictator.speech.v1.SynthesisJobState
	17, // 12: dictator.speech.v1.GetSynthesizeSpeechJobResponse.audio_artifact:type_name -> dictator.speech.v1.ArtifactRef
	18, // 13: dictator.speech.v1.GetSynthesizeSpeechJobResponse.resolved_audio_format:type_name -> dictator.speech.v1.AudioFormat
	1,  // 14: dictator.speech.v1.CancelSynthesizeSpeechJobResponse.state:type_name -> dictator.speech.v1.SynthesisJobState
	3,  // 15: dictator.speech.v1.VoiceService.ExtractReferenceSample:input_type -> dictator.speech.v1.ExtractReferenceSampleRequest
	3,  // 16: dictator.speech.v1.VoiceService.SubmitExtractReferenceSampleJob:input_type -> dictator.speech.v1.ExtractReferenceSampleRequest
	6,  // 17: dictator.speech.v1.VoiceService.GetExtractReferenceSampleJob:input_type -> dictator.speech.v1.GetExtractReferenceSampleJobRequest
	8,  // 18: dictator.speech.v1.VoiceService.CancelExtractReferenceSampleJob:input_type -> dictator.speech.v1.CancelExtractReferenceSampleJobRequest
	10, // 19: dictator.speech.v1.VoiceService.SynthesizeSpeech:input_type -> dictator.speech.v1.SynthesizeSpeechRequest
	10, // 20: dictator.speech.v1.VoiceService.SubmitSynthesizeSpeechJob:input_type -> dictator.speech.v1.SynthesizeSpeechRequest
	13, // 21: dictator.speech.v1.VoiceService.GetSynthesizeSpeechJob:input_type -> dictator.speech.v1.GetSynthesizeSpeechJobRequest
	15, // 22: dictator.speech.v1.VoiceService.CancelSynthesizeSpeechJob:input_type -> dictator.speech.v1.CancelSynthesizeSpeechJobRequest
	4,  // 23: dictator.speech.v1.VoiceService.ExtractReferenceSample:output_type -> dictator.speech.v1.ExtractReferenceSampleResponse
	5,  // 24: dictator.speech.v1.VoiceService.SubmitExtractReferenceSampleJob:output_type -> dictator.speech.v1.SubmitExtractReferenceSampleJobResponse
	7,  // 25: dictator.speech.v1.VoiceService.GetExtractReferenceSampleJob:output_type -> dictator.speech.v1.GetExtractReferenceSampleJobResponse
	9,  // 26: dictator.speech.v1.VoiceService.CancelExtractReferenceSampleJob:output_type -> dictator.speech.v1.CancelExtractReferenceSampleJobResponse
	11, // 27: dictator.speech.v1.VoiceService.SynthesizeSpeech:output_type -> dictator.speech.v1.SynthesizeSpeechResponse
	12, // 28: dictator.speech.v1.VoiceService.SubmitSynthesizeSpeechJob:output_type -> dictator.speech.v1.SubmitSynthesizeSpeechJobResponse
	14, // 29: dictator.speech.v1.VoiceService.GetSynthesizeSpeechJob:output_type -> dictator.speech.v1.GetSynthesizeSpeechJobResponse
	16, // 30: dictator.speech.v1.VoiceService.CancelSynthesizeSpeechJob:output_type -> dictator.speech.v1.CancelSynthesizeSpeechJobResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_dictator_speech_v1_voice_proto_init() }
func file_dictator_speech_v1_voice_proto_init() {
	if File_dictator_speech_v1_voice_proto != nil {
		return
	}
	file_dictator_speech_v1_common_proto_init()
	file_dictator_speech_v1_voice_proto_msgTypes[7].OneofWrappers = []any{
		(*SynthesizeSpeechRequest_Text)(nil),
		(*SynthesizeSpeechRequest_TextArtifactId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictator_speech_v1_voice_proto_rawDesc), len(file_dictator_speech_v1_voice_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dictator_speech_v1_voice_proto_goTypes,
		DependencyIndexes: file_dictator_speech_v1_voice_proto_depIdxs,
		EnumInfos:         file_dictator_speech_v1_voice_proto_enumTypes,
		MessageInfos:      file_dictator_speech_v1_voice_proto_msgTypes,
	}.Build()
	File_dictator_speech_v1_voice_proto = out.File
	file_dictator_speech_v1_voice_proto_goTypes = nil
	file_dictator_speech_v1_voice_proto_depIdxs = nil
}
