# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dictator.speech.v1 import alignment_pb2 as dictator_dot_speech_dot_v1_dot_alignment__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dictator/speech/v1/alignment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlignmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AlignTranscript = channel.unary_unary(
                '/dictator.speech.v1.AlignmentService/AlignTranscript',
                request_serializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.AlignTranscriptRequest.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.AlignTranscriptResponse.FromString,
                _registered_method=True)
        self.SubmitAlignTranscriptJob = channel.unary_unary(
                '/dictator.speech.v1.AlignmentService/SubmitAlignTranscriptJob',
                request_serializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.AlignTranscriptRequest.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.SubmitAlignTranscriptJobResponse.FromString,
                _registered_method=True)
        self.GetAlignTranscriptJob = channel.unary_unary(
                '/dictator.speech.v1.AlignmentService/GetAlignTranscriptJob',
                request_serializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.GetAlignTranscriptJobRequest.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.GetAlignTranscriptJobResponse.FromString,
                _registered_method=True)
        self.CancelAlignTranscriptJob = channel.unary_unary(
                '/dictator.speech.v1.AlignmentService/CancelAlignTranscriptJob',
                request_serializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.CancelAlignTranscriptJobRequest.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.CancelAlignTranscriptJobResponse.FromString,
                _registered_method=True)


class AlignmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AlignTranscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAlignTranscriptJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlignTranscriptJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAlignTranscriptJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlignmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AlignTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.AlignTranscript,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.AlignTranscriptRequest.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.AlignTranscriptResponse.SerializeToString,
            ),
            'SubmitAlignTranscriptJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAlignTranscriptJob,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.AlignTranscriptRequest.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.SubmitAlignTranscriptJobResponse.SerializeToString,
            ),
            'GetAlignTranscriptJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlignTranscriptJob,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.GetAlignTranscriptJobRequest.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.GetAlignTranscriptJobResponse.SerializeToString,
            ),
            'CancelAlignTranscriptJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAlignTranscriptJob,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.CancelAlignTranscriptJobRequest.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_alignment__pb2.CancelAlignTranscriptJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dictator.speech.v1.AlignmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dictator.speech.v1.AlignmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlignmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AlignTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictator.speech.v1.AlignmentService/AlignTranscript',
            dictator_dot_speech_dot_v1_dot_alignment__pb2.AlignTranscriptRequest.SerializeToString,
            dictator_dot_speech_dot_v1_dot_alignment__pb2.AlignTranscriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAlignTranscriptJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictator.speech.v1.AlignmentService/SubmitAlignTranscriptJob',
            dictator_dot_speech_dot_v1_dot_alignment__pb2.AlignTranscriptRequest.SerializeToString,
            dictator_dot_speech_dot_v1_dot_alignment__pb2.SubmitAlignTranscriptJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlignTranscriptJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictator.speech.v1.AlignmentService/GetAlignTranscriptJob',
            dictator_dot_speech_dot_v1_dot_alignment__pb2.GetAlignTranscriptJobRequest.SerializeToString,
            dictator_dot_speech_dot_v1_dot_alignment__pb2.GetAlignTranscriptJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAlignTranscriptJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictator.speech.v1.AlignmentService/CancelAlignTranscriptJob',
            dictator_dot_speech_dot_v1_dot_alignment__pb2.CancelAlignTranscriptJobRequest.SerializeToString,
            dictator_dot_speech_dot_v1_dot_alignment__pb2.CancelAlignTranscriptJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
