# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dictator.speech.v1 import artifacts_pb2 as dictator_dot_speech_dot_v1_dot_artifacts__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dictator/speech/v1/artifacts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArtifactServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadArtifact = channel.stream_unary(
                '/dictator.speech.v1.ArtifactService/UploadArtifact',
                request_serializer=dictator_dot_speech_dot_v1_dot_artifacts__pb2.UploadArtifactChunk.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_artifacts__pb2.UploadArtifactResponse.FromString,
                _registered_method=True)
        self.DownloadArtifact = channel.unary_stream(
                '/dictator.speech.v1.ArtifactService/DownloadArtifact',
                request_serializer=dictator_dot_speech_dot_v1_dot_artifacts__pb2.DownloadArtifactRequest.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_artifacts__pb2.DownloadArtifactChunk.FromString,
                _registered_method=True)


class ArtifactServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadArtifact(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtifactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadArtifact': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadArtifact,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_artifacts__pb2.UploadArtifactChunk.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_artifacts__pb2.UploadArtifactResponse.SerializeToString,
            ),
            'DownloadArtifact': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadArtifact,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_artifacts__pb2.DownloadArtifactRequest.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_artifacts__pb2.DownloadArtifactChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dictator.speech.v1.ArtifactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dictator.speech.v1.ArtifactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtifactService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadArtifact(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dictator.speech.v1.ArtifactService/UploadArtifact',
            dictator_dot_speech_dot_v1_dot_artifacts__pb2.UploadArtifactChunk.SerializeToString,
            dictator_dot_speech_dot_v1_dot_artifacts__pb2.UploadArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dictator.speech.v1.ArtifactService/DownloadArtifact',
            dictator_dot_speech_dot_v1_dot_artifacts__pb2.DownloadArtifactRequest.SerializeToString,
            dictator_dot_speech_dot_v1_dot_artifacts__pb2.DownloadArtifactChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
