# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dictator/speech/v1/runtime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dictator/speech/v1/runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n dictator/speech/v1/runtime.proto\x12\x12\x64ictator.speech.v1\"\x13\n\x11GetMetricsRequest\"\xe1\x01\n\x12GetMetricsResponse\x12\x16\n\x0erequests_total\x18\x01 \x01(\x03\x12\x1a\n\x12requests_succeeded\x18\x02 \x01(\x03\x12\x17\n\x0frequests_failed\x18\x03 \x01(\x03\x12\x10\n\x08inflight\x18\x04 \x01(\x03\x12\x16\n\x0e\x62ytes_received\x18\x05 \x01(\x03\x12\x16\n\x0euptime_seconds\x18\x06 \x01(\x01\x12\x1f\n\x17\x61verage_latency_seconds\x18\x07 \x01(\x01\x12\x1b\n\x13max_latency_seconds\x18\x08 \x01(\x01\x32m\n\x0eRuntimeService\x12[\n\nGetMetrics\x12%.dictator.speech.v1.GetMetricsRequest\x1a&.dictator.speech.v1.GetMetricsResponseBGZEgithub.com/tyemirov/dictator/sdk/go/dictatorspeechv1;dictatorspeechv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dictator.speech.v1.runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZEgithub.com/tyemirov/dictator/sdk/go/dictatorspeechv1;dictatorspeechv1'
  _globals['_GETMETRICSREQUEST']._serialized_start=56
  _globals['_GETMETRICSREQUEST']._serialized_end=75
  _globals['_GETMETRICSRESPONSE']._serialized_start=78
  _globals['_GETMETRICSRESPONSE']._serialized_end=303
  _globals['_RUNTIMESERVICE']._serialized_start=305
  _globals['_RUNTIMESERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
