# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dictator.speech.v1 import voice_pb2 as dictator_dot_speech_dot_v1_dot_voice__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dictator/speech/v1/voice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractReferenceSample = channel.unary_unary(
                '/dictator.speech.v1.VoiceService/ExtractReferenceSample',
                request_serializer=dictator_dot_speech_dot_v1_dot_voice__pb2.ExtractReferenceSampleRequest.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_voice__pb2.ExtractReferenceSampleResponse.FromString,
                _registered_method=True)
        self.SynthesizeSpeech = channel.unary_unary(
                '/dictator.speech.v1.VoiceService/SynthesizeSpeech',
                request_serializer=dictator_dot_speech_dot_v1_dot_voice__pb2.SynthesizeSpeechRequest.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_voice__pb2.SynthesizeSpeechResponse.FromString,
                _registered_method=True)
        self.SubmitSynthesizeSpeechJob = channel.unary_unary(
                '/dictator.speech.v1.VoiceService/SubmitSynthesizeSpeechJob',
                request_serializer=dictator_dot_speech_dot_v1_dot_voice__pb2.SynthesizeSpeechRequest.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_voice__pb2.SubmitSynthesizeSpeechJobResponse.FromString,
                _registered_method=True)
        self.GetSynthesizeSpeechJob = channel.unary_unary(
                '/dictator.speech.v1.VoiceService/GetSynthesizeSpeechJob',
                request_serializer=dictator_dot_speech_dot_v1_dot_voice__pb2.GetSynthesizeSpeechJobRequest.SerializeToString,
                response_deserializer=dictator_dot_speech_dot_v1_dot_voice__pb2.GetSynthesizeSpeechJobResponse.FromString,
                _registered_method=True)


class VoiceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractReferenceSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSynthesizeSpeechJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSynthesizeSpeechJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractReferenceSample': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractReferenceSample,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_voice__pb2.ExtractReferenceSampleRequest.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_voice__pb2.ExtractReferenceSampleResponse.SerializeToString,
            ),
            'SynthesizeSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.SynthesizeSpeech,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_voice__pb2.SynthesizeSpeechRequest.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_voice__pb2.SynthesizeSpeechResponse.SerializeToString,
            ),
            'SubmitSynthesizeSpeechJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSynthesizeSpeechJob,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_voice__pb2.SynthesizeSpeechRequest.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_voice__pb2.SubmitSynthesizeSpeechJobResponse.SerializeToString,
            ),
            'GetSynthesizeSpeechJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSynthesizeSpeechJob,
                    request_deserializer=dictator_dot_speech_dot_v1_dot_voice__pb2.GetSynthesizeSpeechJobRequest.FromString,
                    response_serializer=dictator_dot_speech_dot_v1_dot_voice__pb2.GetSynthesizeSpeechJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dictator.speech.v1.VoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dictator.speech.v1.VoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractReferenceSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictator.speech.v1.VoiceService/ExtractReferenceSample',
            dictator_dot_speech_dot_v1_dot_voice__pb2.ExtractReferenceSampleRequest.SerializeToString,
            dictator_dot_speech_dot_v1_dot_voice__pb2.ExtractReferenceSampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictator.speech.v1.VoiceService/SynthesizeSpeech',
            dictator_dot_speech_dot_v1_dot_voice__pb2.SynthesizeSpeechRequest.SerializeToString,
            dictator_dot_speech_dot_v1_dot_voice__pb2.SynthesizeSpeechResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSynthesizeSpeechJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictator.speech.v1.VoiceService/SubmitSynthesizeSpeechJob',
            dictator_dot_speech_dot_v1_dot_voice__pb2.SynthesizeSpeechRequest.SerializeToString,
            dictator_dot_speech_dot_v1_dot_voice__pb2.SubmitSynthesizeSpeechJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSynthesizeSpeechJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictator.speech.v1.VoiceService/GetSynthesizeSpeechJob',
            dictator_dot_speech_dot_v1_dot_voice__pb2.GetSynthesizeSpeechJobRequest.SerializeToString,
            dictator_dot_speech_dot_v1_dot_voice__pb2.GetSynthesizeSpeechJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
